import { ReactNode } from 'react';

const Tr = ({ children }: { children: ReactNode }) => {
  return (
    <tr className='class="odd:bg-white dark:border-gray-700" border-b even:bg-gray-50 odd:dark:bg-gray-900 even:dark:bg-gray-800'>
      {children}
    </tr>
  );
};

const Td = ({ children }: { children?: ReactNode }) => {
  return <td className="px-2 py-1">{children}</td>;
};

const SpecialCharacters = () => {
  return (
    <div className="relative grid overflow-x-auto">
      <table className="w-fit">
        <tbody>
          <Tr>
            <Td>0</Td>
            <Td>1</Td>
            <Td>2</Td>
            <Td>3</Td>
            <Td>4</Td>
            <Td>5</Td>
            <Td>6</Td>
            <Td>7</Td>
            <Td>8</Td>
            <Td>9</Td>
            <Td>a</Td>
            <Td>b</Td>
            <Td>c</Td>
            <Td>d</Td>
            <Td>e</Td>
            <Td>f</Td>
          </Tr>

          <Tr>
            <Td> </Td>
            <Td>!</Td>
            <Td>&#34;</Td>
            <Td>#</Td>
            <Td>$</Td>
            <Td>%</Td>
            <Td>&amp;</Td>
            <Td>&#39;</Td>
            <Td>(</Td>
            <Td>)</Td>
            <Td>*</Td>
            <Td>+</Td>
            <Td>,</Td>
            <Td>-</Td>
            <Td>.</Td>
            <Td>/</Td>
          </Tr>
          <Tr>
            <Td>0</Td>
            <Td>1</Td>
            <Td>2</Td>
            <Td>3</Td>
            <Td>4</Td>
            <Td>5</Td>
            <Td>6</Td>
            <Td>7</Td>
            <Td>8</Td>
            <Td>9</Td>
            <Td>:</Td>
            <Td>;</Td>
            <Td>&lt;</Td>
            <Td>=</Td>
            <Td>&gt;</Td>
            <Td>?</Td>
          </Tr>
          <Tr>
            <Td>@</Td>
            <Td>A</Td>
            <Td>B</Td>
            <Td>C</Td>
            <Td>D</Td>
            <Td>E</Td>
            <Td>F</Td>
            <Td>G</Td>
            <Td>H</Td>
            <Td>I</Td>
            <Td>J</Td>
            <Td>K</Td>
            <Td>L</Td>
            <Td>M</Td>
            <Td>N</Td>
            <Td>O</Td>
          </Tr>
          <Tr>
            <Td>P</Td>
            <Td>Q</Td>
            <Td>R</Td>
            <Td>S</Td>
            <Td>T</Td>
            <Td>U</Td>
            <Td>V</Td>
            <Td>W</Td>
            <Td>X</Td>
            <Td>Y</Td>
            <Td>Z</Td>
            <Td>[</Td>
            <Td>\</Td>
            <Td>]</Td>
            <Td>^</Td>
            <Td>_</Td>
          </Tr>
          <Tr>
            <Td>`</Td>
            <Td>a</Td>
            <Td>b</Td>
            <Td>c</Td>
            <Td>d</Td>
            <Td>e</Td>
            <Td>f</Td>
            <Td>g</Td>
            <Td>h</Td>
            <Td>i</Td>
            <Td>j</Td>
            <Td>k</Td>
            <Td>l</Td>
            <Td>m</Td>
            <Td>n</Td>
            <Td>o</Td>
          </Tr>
          <Tr>
            <Td>p</Td>
            <Td>q</Td>
            <Td>r</Td>
            <Td>s</Td>
            <Td>t</Td>
            <Td>u</Td>
            <Td>v</Td>
            <Td>w</Td>
            <Td>x</Td>
            <Td>y</Td>
            <Td>z</Td>
            <Td>&#123;</Td>
            <Td>|</Td>
            <Td>&#125;</Td>
            <Td>~</Td>
            <Td></Td>
          </Tr>
          <Tr>
            <Td>€</Td>
            <Td></Td>
            <Td>‚</Td>
            <Td>ƒ</Td>
            <Td>„</Td>
            <Td>…</Td>
            <Td>†</Td>
            <Td>‡</Td>
            <Td>ˆ</Td>
            <Td>‰</Td>
            <Td>Š</Td>
            <Td>‹</Td>
            <Td>Œ</Td>
            <Td></Td>
            <Td>Ž</Td>
            <Td></Td>
          </Tr>
          <Tr>
            <Td></Td>
            <Td>‘</Td>
            <Td>’</Td>
            <Td>“</Td>
            <Td>”</Td>
            <Td>•</Td>
            <Td>–</Td>
            <Td>—</Td>
            <Td>˜</Td>
            <Td>™</Td>
            <Td>š</Td>
            <Td>›</Td>
            <Td>œ</Td>
            <Td></Td>
            <Td>ž</Td>
            <Td>Ÿ</Td>
          </Tr>
          <Tr>
            <Td>&nbsp;</Td>
            <Td>¡</Td>
            <Td>¢</Td>
            <Td>£</Td>
            <Td>¤</Td>
            <Td>¥</Td>
            <Td>¦</Td>
            <Td>§</Td>
            <Td>¨</Td>
            <Td>©</Td>
            <Td>ª</Td>
            <Td>«</Td>
            <Td>¬</Td>
            <Td>­</Td>
            <Td>®</Td>
            <Td>¯</Td>
          </Tr>
          <Tr>
            <Td>°</Td>
            <Td>±</Td>
            <Td>²</Td>
            <Td>³</Td>
            <Td>´</Td>
            <Td>µ</Td>
            <Td>¶</Td>
            <Td>·</Td>
            <Td>¸</Td>
            <Td>¹</Td>
            <Td>º</Td>
            <Td>»</Td>
            <Td>¼</Td>
            <Td>½</Td>
            <Td>¾</Td>
            <Td>¿</Td>
          </Tr>
          <Tr>
            <Td>À</Td>
            <Td>Á</Td>
            <Td>Â</Td>
            <Td>Ã</Td>
            <Td>Ä</Td>
            <Td>Å</Td>
            <Td>Æ</Td>
            <Td>Ç</Td>
            <Td>È</Td>
            <Td>É</Td>
            <Td>Ê</Td>
            <Td>Ë</Td>
            <Td>Ì</Td>
            <Td>Í</Td>
            <Td>Î</Td>
            <Td>Ï</Td>
          </Tr>
          <Tr>
            <Td>Ð</Td>
            <Td>Ñ</Td>
            <Td>Ò</Td>
            <Td>Ó</Td>
            <Td>Ô</Td>
            <Td>Õ</Td>
            <Td>Ö</Td>
            <Td>×</Td>
            <Td>Ø</Td>
            <Td>Ù</Td>
            <Td>Ú</Td>
            <Td>Û</Td>
            <Td>Ü</Td>
            <Td>Ý</Td>
            <Td>Þ</Td>
            <Td>ß</Td>
          </Tr>
          <Tr>
            <Td>à</Td>
            <Td>á</Td>
            <Td>â</Td>
            <Td>ã</Td>
            <Td>ä</Td>
            <Td>å</Td>
            <Td>æ</Td>
            <Td>ç</Td>
            <Td>è</Td>
            <Td>é</Td>
            <Td>ê</Td>
            <Td>ë</Td>
            <Td>ì</Td>
            <Td>í</Td>
            <Td>î</Td>
            <Td>ï</Td>
          </Tr>
          <Tr>
            <Td>ð</Td>
            <Td>ñ</Td>
            <Td>ò</Td>
            <Td>ó</Td>
            <Td>ô</Td>
            <Td>õ</Td>
            <Td>ö</Td>
            <Td>÷</Td>
            <Td>ø</Td>
            <Td>ù</Td>
            <Td>ú</Td>
            <Td>û</Td>
            <Td>ü</Td>
            <Td>ý</Td>
            <Td>þ</Td>
            <Td>ÿ</Td>
          </Tr>
          <Tr>
            <Td>Ā</Td>
            <Td>ā</Td>
            <Td>Ă</Td>
            <Td>ă</Td>
            <Td>Ą</Td>
            <Td>ą</Td>
            <Td>Ć</Td>
            <Td>ć</Td>
            <Td>Ĉ</Td>
            <Td>ĉ</Td>
            <Td>Ċ</Td>
            <Td>ċ</Td>
            <Td>Č</Td>
            <Td>č</Td>
            <Td>Ď</Td>
            <Td>ď</Td>
          </Tr>
          <Tr>
            <Td>Đ</Td>
            <Td>đ</Td>
            <Td>Ē</Td>
            <Td>ē</Td>
            <Td>Ĕ</Td>
            <Td>ĕ</Td>
            <Td>Ė</Td>
            <Td>ė</Td>
            <Td>Ę</Td>
            <Td>ę</Td>
            <Td>Ě</Td>
            <Td>ě</Td>
            <Td>Ĝ</Td>
            <Td>ĝ</Td>
            <Td>Ğ</Td>
            <Td>ğ</Td>
          </Tr>
          <Tr>
            <Td>Ġ</Td>
            <Td>ġ</Td>
            <Td>Ģ</Td>
            <Td>ģ</Td>
            <Td>Ĥ</Td>
            <Td>ĥ</Td>
            <Td>Ħ</Td>
            <Td>ħ</Td>
            <Td>Ĩ</Td>
            <Td>ĩ</Td>
            <Td>Ī</Td>
            <Td>ī</Td>
            <Td>Ĭ</Td>
            <Td>ĭ</Td>
            <Td>Į</Td>
            <Td>į</Td>
          </Tr>
          <Tr>
            <Td>İ</Td>
            <Td>ı</Td>
            <Td>Ĳ</Td>
            <Td>ĳ</Td>
            <Td>Ĵ</Td>
            <Td>ĵ</Td>
            <Td>Ķ</Td>
            <Td>ķ</Td>
            <Td>ĸ</Td>
            <Td>Ĺ</Td>
            <Td>ĺ</Td>
            <Td>Ļ</Td>
            <Td>ļ</Td>
            <Td>Ľ</Td>
            <Td>ľ</Td>
            <Td>Ŀ</Td>
          </Tr>
          <Tr>
            <Td>ŀ</Td>
            <Td>Ł</Td>
            <Td>ł</Td>
            <Td>Ń</Td>
            <Td>ń</Td>
            <Td>Ņ</Td>
            <Td>ņ</Td>
            <Td>Ň</Td>
            <Td>ň</Td>
            <Td>ŉ</Td>
            <Td>Ŋ</Td>
            <Td>ŋ</Td>
            <Td>Ō</Td>
            <Td>ō</Td>
            <Td>Ŏ</Td>
            <Td>ŏ</Td>
          </Tr>
          <Tr>
            <Td>Ő</Td>
            <Td>ő</Td>
            <Td>Œ</Td>
            <Td>œ</Td>
            <Td>Ŕ</Td>
            <Td>ŕ</Td>
            <Td>Ŗ</Td>
            <Td>ŗ</Td>
            <Td>Ř</Td>
            <Td>ř</Td>
            <Td>Ś</Td>
            <Td>ś</Td>
            <Td>Ŝ</Td>
            <Td>ŝ</Td>
            <Td>Ş</Td>
            <Td>ş</Td>
          </Tr>
          <Tr>
            <Td>Š</Td>
            <Td>š</Td>
            <Td>Ţ</Td>
            <Td>ţ</Td>
            <Td>Ť</Td>
            <Td>ť</Td>
            <Td>Ŧ</Td>
            <Td>ŧ</Td>
            <Td>Ũ</Td>
            <Td>ũ</Td>
            <Td>Ū</Td>
            <Td>ū</Td>
            <Td>Ŭ</Td>
            <Td>ŭ</Td>
            <Td>Ů</Td>
            <Td>ů</Td>
          </Tr>
          <Tr>
            <Td>Ű</Td>
            <Td>ű</Td>
            <Td>Ų</Td>
            <Td>ų</Td>
            <Td>Ŵ</Td>
            <Td>ŵ</Td>
            <Td>Ŷ</Td>
            <Td>ŷ</Td>
            <Td>Ÿ</Td>
            <Td>Ź</Td>
            <Td>ź</Td>
            <Td>Ż</Td>
            <Td>ż</Td>
            <Td>Ž</Td>
            <Td>ž</Td>
            <Td>ſ</Td>
          </Tr>
          <Tr>
            <Td>ƀ</Td>
            <Td>Ɓ</Td>
            <Td>Ƃ</Td>
            <Td>ƃ</Td>
            <Td>Ƅ</Td>
            <Td>ƅ</Td>
            <Td>Ɔ</Td>
            <Td>Ƈ</Td>
            <Td>ƈ</Td>
            <Td>Ɖ</Td>
            <Td>Ɗ</Td>
            <Td>Ƌ</Td>
            <Td>ƌ</Td>
            <Td>ƍ</Td>
            <Td>Ǝ</Td>
            <Td>Ə</Td>
          </Tr>
          <Tr>
            <Td>Ɛ</Td>
            <Td>Ƒ</Td>
            <Td>ƒ</Td>
            <Td>Ɠ</Td>
            <Td>Ɣ</Td>
            <Td>ƕ</Td>
            <Td>Ɩ</Td>
            <Td>Ɨ</Td>
            <Td>Ƙ</Td>
            <Td>ƙ</Td>
            <Td>ƚ</Td>
            <Td>ƛ</Td>
            <Td>Ɯ</Td>
            <Td>Ɲ</Td>
            <Td>ƞ</Td>
            <Td>Ɵ</Td>
          </Tr>
          <Tr>
            <Td>Ơ</Td>
            <Td>ơ</Td>
            <Td>Ƣ</Td>
            <Td>ƣ</Td>
            <Td>Ƥ</Td>
            <Td>ƥ</Td>
            <Td>Ʀ</Td>
            <Td>Ƨ</Td>
            <Td>ƨ</Td>
            <Td>Ʃ</Td>
            <Td>ƪ</Td>
            <Td>ƫ</Td>
            <Td>Ƭ</Td>
            <Td>ƭ</Td>
            <Td>Ʈ</Td>
            <Td>Ư</Td>
          </Tr>
          <Tr>
            <Td>ư</Td>
            <Td>Ʊ</Td>
            <Td>Ʋ</Td>
            <Td>Ƴ</Td>
            <Td>ƴ</Td>
            <Td>Ƶ</Td>
            <Td>ƶ</Td>
            <Td>Ʒ</Td>
            <Td>Ƹ</Td>
            <Td>ƹ</Td>
            <Td>ƺ</Td>
            <Td>ƻ</Td>
            <Td>Ƽ</Td>
            <Td>ƽ</Td>
            <Td>ƾ</Td>
            <Td>ƿ</Td>
          </Tr>
          <Tr>
            <Td>ǀ</Td>
            <Td>ǁ</Td>
            <Td>ǂ</Td>
            <Td>ǃ</Td>
            <Td>Ǆ</Td>
            <Td>ǅ</Td>
            <Td>ǆ</Td>
            <Td>Ǉ</Td>
            <Td>ǈ</Td>
            <Td>ǉ</Td>
            <Td>Ǌ</Td>
            <Td>ǋ</Td>
            <Td>ǌ</Td>
            <Td>Ǎ</Td>
            <Td>ǎ</Td>
            <Td>Ǐ</Td>
          </Tr>
          <Tr>
            <Td>ǐ</Td>
            <Td>Ǒ</Td>
            <Td>ǒ</Td>
            <Td>Ǔ</Td>
            <Td>ǔ</Td>
            <Td>Ǖ</Td>
            <Td>ǖ</Td>
            <Td>Ǘ</Td>
            <Td>ǘ</Td>
            <Td>Ǚ</Td>
            <Td>ǚ</Td>
            <Td>Ǜ</Td>
            <Td>ǜ</Td>
            <Td>ǝ</Td>
            <Td>Ǟ</Td>
            <Td>ǟ</Td>
          </Tr>
          <Tr>
            <Td>Ǡ</Td>
            <Td>ǡ</Td>
            <Td>Ǣ</Td>
            <Td>ǣ</Td>
            <Td>Ǥ</Td>
            <Td>ǥ</Td>
            <Td>Ǧ</Td>
            <Td>ǧ</Td>
            <Td>Ǩ</Td>
            <Td>ǩ</Td>
            <Td>Ǫ</Td>
            <Td>ǫ</Td>
            <Td>Ǭ</Td>
            <Td>ǭ</Td>
            <Td>Ǯ</Td>
            <Td>ǯ</Td>
          </Tr>
          <Tr>
            <Td>ǰ</Td>
            <Td>Ǳ</Td>
            <Td>ǲ</Td>
            <Td>ǳ</Td>
            <Td>Ǵ</Td>
            <Td>ǵ</Td>
            <Td>Ƕ</Td>
            <Td>Ƿ</Td>
            <Td>Ǹ</Td>
            <Td>ǹ</Td>
            <Td>Ǻ</Td>
            <Td>ǻ</Td>
            <Td>Ǽ</Td>
            <Td>ǽ</Td>
            <Td>Ǿ</Td>
            <Td>ǿ</Td>
          </Tr>
          <Tr>
            <Td>0</Td>
            <Td>1</Td>
            <Td>2</Td>
            <Td>3</Td>
            <Td>4</Td>
            <Td>5</Td>
            <Td>6</Td>
            <Td>7</Td>
            <Td>8</Td>
            <Td>9</Td>
            <Td>a</Td>
            <Td>b</Td>
            <Td>c</Td>
            <Td>d</Td>
            <Td>e</Td>
            <Td>f</Td>
          </Tr>
          <Tr>
            <Td>Ȁ</Td>
            <Td>ȁ</Td>
            <Td>Ȃ</Td>
            <Td>ȃ</Td>
            <Td>Ȅ</Td>
            <Td>ȅ</Td>
            <Td>Ȇ</Td>
            <Td>ȇ</Td>
            <Td>Ȉ</Td>
            <Td>ȉ</Td>
            <Td>Ȋ</Td>
            <Td>ȋ</Td>
            <Td>Ȍ</Td>
            <Td>ȍ</Td>
            <Td>Ȏ</Td>
            <Td>ȏ</Td>
          </Tr>
          <Tr>
            <Td>Ȑ</Td>
            <Td>ȑ</Td>
            <Td>Ȓ</Td>
            <Td>ȓ</Td>
            <Td>Ȕ</Td>
            <Td>ȕ</Td>
            <Td>Ȗ</Td>
            <Td>ȗ</Td>
            <Td>Ș</Td>
            <Td>ș</Td>
            <Td>Ț</Td>
            <Td>ț</Td>
            <Td>Ȝ</Td>
            <Td>ȝ</Td>
            <Td>Ȟ</Td>
            <Td>ȟ</Td>
          </Tr>
          <Tr>
            <Td>Ƞ</Td>
            <Td>ȡ</Td>
            <Td>Ȣ</Td>
            <Td>ȣ</Td>
            <Td>Ȥ</Td>
            <Td>ȥ</Td>
            <Td>Ȧ</Td>
            <Td>ȧ</Td>
            <Td>Ȩ</Td>
            <Td>ȩ</Td>
            <Td>Ȫ</Td>
            <Td>ȫ</Td>
            <Td>Ȭ</Td>
            <Td>ȭ</Td>
            <Td>Ȯ</Td>
            <Td>ȯ</Td>
          </Tr>
          <Tr>
            <Td>Ȱ</Td>
            <Td>ȱ</Td>
            <Td>Ȳ</Td>
            <Td>ȳ</Td>
            <Td>ȴ</Td>
            <Td>ȵ</Td>
            <Td>ȶ</Td>
            <Td>ȷ</Td>
            <Td>ȸ</Td>
            <Td>ȹ</Td>
            <Td>Ⱥ</Td>
            <Td>Ȼ</Td>
            <Td>ȼ</Td>
            <Td>Ƚ</Td>
            <Td>Ⱦ</Td>
            <Td>ȿ</Td>
          </Tr>
          <Tr>
            <Td>ɀ</Td>
            <Td>Ɂ</Td>
            <Td>ɂ</Td>
            <Td>Ƀ</Td>
            <Td>Ʉ</Td>
            <Td>Ʌ</Td>
            <Td>Ɇ</Td>
            <Td>ɇ</Td>
            <Td>Ɉ</Td>
            <Td>ɉ</Td>
            <Td>Ɋ</Td>
            <Td>ɋ</Td>
            <Td>Ɍ</Td>
            <Td>ɍ</Td>
            <Td>Ɏ</Td>
            <Td>ɏ</Td>
          </Tr>
          <Tr>
            <Td>ɐ</Td>
            <Td>ɑ</Td>
            <Td>ɒ</Td>
            <Td>ɓ</Td>
            <Td>ɔ</Td>
            <Td>ɕ</Td>
            <Td>ɖ</Td>
            <Td>ɗ</Td>
            <Td>ɘ</Td>
            <Td>ə</Td>
            <Td>ɚ</Td>
            <Td>ɛ</Td>
            <Td>ɜ</Td>
            <Td>ɝ</Td>
            <Td>ɞ</Td>
            <Td>ɟ</Td>
          </Tr>
          <Tr>
            <Td>ɠ</Td>
            <Td>ɡ</Td>
            <Td>ɢ</Td>
            <Td>ɣ</Td>
            <Td>ɤ</Td>
            <Td>ɥ</Td>
            <Td>ɦ</Td>
            <Td>ɧ</Td>
            <Td>ɨ</Td>
            <Td>ɩ</Td>
            <Td>ɪ</Td>
            <Td>ɫ</Td>
            <Td>ɬ</Td>
            <Td>ɭ</Td>
            <Td>ɮ</Td>
            <Td>ɯ</Td>
          </Tr>
          <Tr>
            <Td>ɰ</Td>
            <Td>ɱ</Td>
            <Td>ɲ</Td>
            <Td>ɳ</Td>
            <Td>ɴ</Td>
            <Td>ɵ</Td>
            <Td>ɶ</Td>
            <Td>ɷ</Td>
            <Td>ɸ</Td>
            <Td>ɹ</Td>
            <Td>ɺ</Td>
            <Td>ɻ</Td>
            <Td>ɼ</Td>
            <Td>ɽ</Td>
            <Td>ɾ</Td>
            <Td>ɿ</Td>
          </Tr>
          <Tr>
            <Td>ʀ</Td>
            <Td>ʁ</Td>
            <Td>ʂ</Td>
            <Td>ʃ</Td>
            <Td>ʄ</Td>
            <Td>ʅ</Td>
            <Td>ʆ</Td>
            <Td>ʇ</Td>
            <Td>ʈ</Td>
            <Td>ʉ</Td>
            <Td>ʊ</Td>
            <Td>ʋ</Td>
            <Td>ʌ</Td>
            <Td>ʍ</Td>
            <Td>ʎ</Td>
            <Td>ʏ</Td>
          </Tr>
          <Tr>
            <Td>ʐ</Td>
            <Td>ʑ</Td>
            <Td>ʒ</Td>
            <Td>ʓ</Td>
            <Td>ʔ</Td>
            <Td>ʕ</Td>
            <Td>ʖ</Td>
            <Td>ʗ</Td>
            <Td>ʘ</Td>
            <Td>ʙ</Td>
            <Td>ʚ</Td>
            <Td>ʛ</Td>
            <Td>ʜ</Td>
            <Td>ʝ</Td>
            <Td>ʞ</Td>
            <Td>ʟ</Td>
          </Tr>
          <Tr>
            <Td>ʠ</Td>
            <Td>ʡ</Td>
            <Td>ʢ</Td>
            <Td>ʣ</Td>
            <Td>ʤ</Td>
            <Td>ʥ</Td>
            <Td>ʦ</Td>
            <Td>ʧ</Td>
            <Td>ʨ</Td>
            <Td>ʩ</Td>
            <Td>ʪ</Td>
            <Td>ʫ</Td>
            <Td>ʬ</Td>
            <Td>ʭ</Td>
            <Td>ʮ</Td>
            <Td>ʯ</Td>
          </Tr>
          <Tr>
            <Td>ʰ</Td>
            <Td>ʱ</Td>
            <Td>ʲ</Td>
            <Td>ʳ</Td>
            <Td>ʴ</Td>
            <Td>ʵ</Td>
            <Td>ʶ</Td>
            <Td>ʷ</Td>
            <Td>ʸ</Td>
            <Td>ʹ</Td>
            <Td>ʺ</Td>
            <Td>ʻ</Td>
            <Td>ʼ</Td>
            <Td>ʽ</Td>
            <Td>ʾ</Td>
            <Td>ʿ</Td>
          </Tr>
          <Tr>
            <Td>ˀ</Td>
            <Td>ˁ</Td>
            <Td>˂</Td>
            <Td>˃</Td>
            <Td>˄</Td>
            <Td>˅</Td>
            <Td>ˆ</Td>
            <Td>ˇ</Td>
            <Td>ˈ</Td>
            <Td>ˉ</Td>
            <Td>ˊ</Td>
            <Td>ˋ</Td>
            <Td>ˌ</Td>
            <Td>ˍ</Td>
            <Td>ˎ</Td>
            <Td>ˏ</Td>
          </Tr>
          <Tr>
            <Td>ː</Td>
            <Td>ˑ</Td>
            <Td>˒</Td>
            <Td>˓</Td>
            <Td>˔</Td>
            <Td>˕</Td>
            <Td>˖</Td>
            <Td>˗</Td>
            <Td>˘</Td>
            <Td>˙</Td>
            <Td>˚</Td>
            <Td>˛</Td>
            <Td>˜</Td>
            <Td>˝</Td>
            <Td>˞</Td>
            <Td>˟</Td>
          </Tr>
          <Tr>
            <Td>ˠ</Td>
            <Td>ˡ</Td>
            <Td>ˢ</Td>
            <Td>ˣ</Td>
            <Td>ˤ</Td>
            <Td>˥</Td>
            <Td>˦</Td>
            <Td>˧</Td>
            <Td>˨</Td>
            <Td>˩</Td>
            <Td>˪</Td>
            <Td>˫</Td>
            <Td>ˬ</Td>
            <Td>˭</Td>
            <Td>ˮ</Td>
            <Td>˯</Td>
          </Tr>
          <Tr>
            <Td>˰</Td>
            <Td>˱</Td>
            <Td>˲</Td>
            <Td>˳</Td>
            <Td>˴</Td>
            <Td>˵</Td>
            <Td>˶</Td>
            <Td>˷</Td>
            <Td>˸</Td>
            <Td>˹</Td>
            <Td>˺</Td>
            <Td>˻</Td>
            <Td>˼</Td>
            <Td>˽</Td>
            <Td>˾</Td>
            <Td>˿</Td>
          </Tr>
          <Tr>
            <Td>̀</Td>
            <Td>́</Td>
            <Td>̂</Td>
            <Td>̃</Td>
            <Td>̄</Td>
            <Td>̅</Td>
            <Td>̆</Td>
            <Td>̇</Td>
            <Td>̈</Td>
            <Td>̉</Td>
            <Td>̊</Td>
            <Td>̋</Td>
            <Td>̌</Td>
            <Td>̍</Td>
            <Td>̎</Td>
            <Td>̏</Td>
          </Tr>
          <Tr>
            <Td>̐</Td>
            <Td>̑</Td>
            <Td>̒</Td>
            <Td>̓</Td>
            <Td>̔</Td>
            <Td>̕</Td>
            <Td>̖</Td>
            <Td>̗</Td>
            <Td>̘</Td>
            <Td>̙</Td>
            <Td>̚</Td>
            <Td>̛</Td>
            <Td>̜</Td>
            <Td>̝</Td>
            <Td>̞</Td>
            <Td>̟</Td>
          </Tr>
          <Tr>
            <Td>̠</Td>
            <Td>̡</Td>
            <Td>̢</Td>
            <Td>̣</Td>
            <Td>̤</Td>
            <Td>̥</Td>
            <Td>̦</Td>
            <Td>̧</Td>
            <Td>̨</Td>
            <Td>̩</Td>
            <Td>̪</Td>
            <Td>̫</Td>
            <Td>̬</Td>
            <Td>̭</Td>
            <Td>̮</Td>
            <Td>̯</Td>
          </Tr>
          <Tr>
            <Td>̰</Td>
            <Td>̱</Td>
            <Td>̲</Td>
            <Td>̳</Td>
            <Td>̴</Td>
            <Td>̵</Td>
            <Td>̶</Td>
            <Td>̷</Td>
            <Td≯</Td>
            <Td>̹</Td>
            <Td>̺</Td>
            <Td>̻</Td>
            <Td>̼</Td>
            <Td>̽</Td>
            <Td>̾</Td>
            <Td>̿</Td>
          </Tr>
          <Tr>
            <Td>̀</Td>
            <Td>́</Td>
            <Td>͂</Td>
            <Td>̓</Td>
            <Td>̈́</Td>
            <Td>ͅ</Td>
            <Td>͆</Td>
            <Td>͇</Td>
            <Td>͈</Td>
            <Td>͉</Td>
            <Td>͊</Td>
            <Td>͋</Td>
            <Td>͌</Td>
            <Td>͍</Td>
            <Td>͎</Td>
            <Td>͏</Td>
          </Tr>
          <Tr>
            <Td>͐</Td>
            <Td>͑</Td>
            <Td>͒</Td>
            <Td>͓</Td>
            <Td>͔</Td>
            <Td>͕</Td>
            <Td>͖</Td>
            <Td>͗</Td>
            <Td>͘</Td>
            <Td>͙</Td>
            <Td>͚</Td>
            <Td>͛</Td>
            <Td>͜</Td>
            <Td>͝</Td>
            <Td>͞</Td>
            <Td>͟</Td>
          </Tr>
          <Tr>
            <Td>͠</Td>
            <Td>͡</Td>
            <Td>͢</Td>
            <Td>ͣ</Td>
            <Td>ͤ</Td>
            <Td>ͥ</Td>
            <Td>ͦ</Td>
            <Td>ͧ</Td>
            <Td>ͨ</Td>
            <Td>ͩ</Td>
            <Td>ͪ</Td>
            <Td>ͫ</Td>
            <Td>ͬ</Td>
            <Td>ͭ</Td>
            <Td>ͮ</Td>
            <Td>ͯ</Td>
          </Tr>
          <Tr>
            <Td>Ͱ</Td>
            <Td>ͱ</Td>
            <Td>Ͳ</Td>
            <Td>ͳ</Td>
            <Td>ʹ</Td>
            <Td>͵</Td>
            <Td>Ͷ</Td>
            <Td>ͷ</Td>
            <Td>͸</Td>
            <Td>͹</Td>
            <Td>ͺ</Td>
            <Td>ͻ</Td>
            <Td>ͼ</Td>
            <Td>ͽ</Td>
            <Td>;</Td>
            <Td>Ϳ</Td>
          </Tr>
          <Tr>
            <Td>΀</Td>
            <Td>΁</Td>
            <Td>΂</Td>
            <Td>΃</Td>
            <Td>΄</Td>
            <Td>΅</Td>
            <Td>Ά</Td>
            <Td>·</Td>
            <Td>Έ</Td>
            <Td>Ή</Td>
            <Td>Ί</Td>
            <Td>΋</Td>
            <Td>Ό</Td>
            <Td>΍</Td>
            <Td>Ύ</Td>
            <Td>Ώ</Td>
          </Tr>
          <Tr>
            <Td>ΐ</Td>
            <Td>Α</Td>
            <Td>Β</Td>
            <Td>Γ</Td>
            <Td>Δ</Td>
            <Td>Ε</Td>
            <Td>Ζ</Td>
            <Td>Η</Td>
            <Td>Θ</Td>
            <Td>Ι</Td>
            <Td>Κ</Td>
            <Td>Λ</Td>
            <Td>Μ</Td>
            <Td>Ν</Td>
            <Td>Ξ</Td>
            <Td>Ο</Td>
          </Tr>
          <Tr>
            <Td>Π</Td>
            <Td>Ρ</Td>
            <Td>΢</Td>
            <Td>Σ</Td>
            <Td>Τ</Td>
            <Td>Υ</Td>
            <Td>Φ</Td>
            <Td>Χ</Td>
            <Td>Ψ</Td>
            <Td>Ω</Td>
            <Td>Ϊ</Td>
            <Td>Ϋ</Td>
            <Td>ά</Td>
            <Td>έ</Td>
            <Td>ή</Td>
            <Td>ί</Td>
          </Tr>
          <Tr>
            <Td>ΰ</Td>
            <Td>α</Td>
            <Td>β</Td>
            <Td>γ</Td>
            <Td>δ</Td>
            <Td>ε</Td>
            <Td>ζ</Td>
            <Td>η</Td>
            <Td>θ</Td>
            <Td>ι</Td>
            <Td>κ</Td>
            <Td>λ</Td>
            <Td>μ</Td>
            <Td>ν</Td>
            <Td>ξ</Td>
            <Td>ο</Td>
          </Tr>
          <Tr>
            <Td>π</Td>
            <Td>ρ</Td>
            <Td>ς</Td>
            <Td>σ</Td>
            <Td>τ</Td>
            <Td>υ</Td>
            <Td>φ</Td>
            <Td>χ</Td>
            <Td>ψ</Td>
            <Td>ω</Td>
            <Td>ϊ</Td>
            <Td>ϋ</Td>
            <Td>ό</Td>
            <Td>ύ</Td>
            <Td>ώ</Td>
            <Td>Ϗ</Td>
          </Tr>
          <Tr>
            <Td>ϐ</Td>
            <Td>ϑ</Td>
            <Td>ϒ</Td>
            <Td>ϓ</Td>
            <Td>ϔ</Td>
            <Td>ϕ</Td>
            <Td>ϖ</Td>
            <Td>ϗ</Td>
            <Td>Ϙ</Td>
            <Td>ϙ</Td>
            <Td>Ϛ</Td>
            <Td>ϛ</Td>
            <Td>Ϝ</Td>
            <Td>ϝ</Td>
            <Td>Ϟ</Td>
            <Td>ϟ</Td>
          </Tr>
          <Tr>
            <Td>Ϡ</Td>
            <Td>ϡ</Td>
            <Td>Ϣ</Td>
            <Td>ϣ</Td>
            <Td>Ϥ</Td>
            <Td>ϥ</Td>
            <Td>Ϧ</Td>
            <Td>ϧ</Td>
            <Td>Ϩ</Td>
            <Td>ϩ</Td>
            <Td>Ϫ</Td>
            <Td>ϫ</Td>
            <Td>Ϭ</Td>
            <Td>ϭ</Td>
            <Td>Ϯ</Td>
            <Td>ϯ</Td>
          </Tr>
          <Tr>
            <Td>0</Td>
            <Td>1</Td>
            <Td>2</Td>
            <Td>3</Td>
            <Td>4</Td>
            <Td>5</Td>
            <Td>6</Td>
            <Td>7</Td>
            <Td>8</Td>
            <Td>9</Td>
            <Td>a</Td>
            <Td>b</Td>
            <Td>c</Td>
            <Td>d</Td>
            <Td>e</Td>
            <Td>f</Td>
          </Tr>
          <Tr>
            <Td> </Td>
            <Td> </Td>
            <Td> </Td>
            <Td> </Td>
            <Td> </Td>
            <Td> </Td>
            <Td> </Td>
            <Td> </Td>
            <Td> </Td>
            <Td> </Td>
            <Td> </Td>
            <Td>​</Td>
            <Td>‌</Td>
            <Td>‍</Td>
            <Td>‎</Td>
            <Td>‏</Td>
          </Tr>
          <Tr>
            <Td>‐</Td>
            <Td>‑</Td>
            <Td>‒</Td>
            <Td>–</Td>
            <Td>—</Td>
            <Td>―</Td>
            <Td>‖</Td>
            <Td>‗</Td>
            <Td>‘</Td>
            <Td>’</Td>
            <Td>‚</Td>
            <Td>‛</Td>
            <Td>“</Td>
            <Td>”</Td>
            <Td>„</Td>
            <Td>‟</Td>
          </Tr>
          <Tr>
            <Td>†</Td>
            <Td>‡</Td>
            <Td>•</Td>
            <Td>‣</Td>
            <Td>․</Td>
            <Td>‥</Td>
            <Td>…</Td>
            <Td>‧</Td>
            <Td></Td>
            <Td></Td>
            <Td>‪</Td>
            <Td>‫</Td>
            <Td>‬</Td>
            <Td>‭</Td>
            <Td>‮</Td>
            <Td> </Td>
          </Tr>
          <Tr>
            <Td>‰</Td>
            <Td>‱</Td>
            <Td>′</Td>
            <Td>″</Td>
            <Td>‴</Td>
            <Td>‵</Td>
            <Td>‶</Td>
            <Td>‷</Td>
            <Td>‸</Td>
            <Td>‹</Td>
            <Td>›</Td>
            <Td>※</Td>
            <Td>‼</Td>
            <Td>‽</Td>
            <Td>‾</Td>
            <Td>‿</Td>
          </Tr>
          <Tr>
            <Td>⁀</Td>
            <Td>⁁</Td>
            <Td>⁂</Td>
            <Td>⁃</Td>
            <Td>⁄</Td>
            <Td>⁅</Td>
            <Td>⁆</Td>
            <Td>⁇</Td>
            <Td>⁈</Td>
            <Td>⁉</Td>
            <Td>⁊</Td>
            <Td>⁋</Td>
            <Td>⁌</Td>
            <Td>⁍</Td>
            <Td>⁎</Td>
            <Td>⁏</Td>
          </Tr>
          <Tr>
            <Td>⁐</Td>
            <Td>⁑</Td>
            <Td>⁒</Td>
            <Td>⁓</Td>
            <Td>⁔</Td>
            <Td>⁕</Td>
            <Td>⁖</Td>
            <Td>⁗</Td>
            <Td>⁘</Td>
            <Td>⁙</Td>
            <Td>⁚</Td>
            <Td>⁛</Td>
            <Td>⁜</Td>
            <Td>⁝</Td>
            <Td>⁞</Td>
            <Td> </Td>
          </Tr>
          <Tr>
            <Td>⁠</Td>
            <Td>⁡</Td>
            <Td>⁢</Td>
            <Td>⁣</Td>
            <Td>⁤</Td>
            <Td>⁥</Td>
            <Td>⁦</Td>
            <Td>⁧</Td>
            <Td>⁨</Td>
            <Td>⁩</Td>
            <Td>⁪</Td>
            <Td>⁫</Td>
            <Td>⁬</Td>
            <Td>⁭</Td>
            <Td>⁮</Td>
            <Td>⁯</Td>
          </Tr>
          <Tr>
            <Td>⁰</Td>
            <Td>ⁱ</Td>
            <Td>⁲</Td>
            <Td>⁳</Td>
            <Td>⁴</Td>
            <Td>⁵</Td>
            <Td>⁶</Td>
            <Td>⁷</Td>
            <Td>⁸</Td>
            <Td>⁹</Td>
            <Td>⁺</Td>
            <Td>⁻</Td>
            <Td>⁼</Td>
            <Td>⁽</Td>
            <Td>⁾</Td>
            <Td>ⁿ</Td>
          </Tr>
          <Tr>
            <Td>₀</Td>
            <Td>₁</Td>
            <Td>₂</Td>
            <Td>₃</Td>
            <Td>₄</Td>
            <Td>₅</Td>
            <Td>₆</Td>
            <Td>₇</Td>
            <Td>₈</Td>
            <Td>₉</Td>
            <Td>₊</Td>
            <Td>₋</Td>
            <Td>₌</Td>
            <Td>₍</Td>
            <Td>₎</Td>
            <Td>₏</Td>
          </Tr>
          <Tr>
            <Td>ₐ</Td>
            <Td>ₑ</Td>
            <Td>ₒ</Td>
            <Td>ₓ</Td>
            <Td>ₔ</Td>
            <Td>ₕ</Td>
            <Td>ₖ</Td>
            <Td>ₗ</Td>
            <Td>ₘ</Td>
            <Td>ₙ</Td>
            <Td>ₚ</Td>
            <Td>ₛ</Td>
            <Td>ₜ</Td>
            <Td>₝</Td>
            <Td>₞</Td>
            <Td>₟</Td>
          </Tr>
          <Tr>
            <Td>₠</Td>
            <Td>₡</Td>
            <Td>₢</Td>
            <Td>₣</Td>
            <Td>₤</Td>
            <Td>₥</Td>
            <Td>₦</Td>
            <Td>₧</Td>
            <Td>₨</Td>
            <Td>₩</Td>
            <Td>₪</Td>
            <Td>₫</Td>
            <Td>€</Td>
            <Td>₭</Td>
            <Td>₮</Td>
            <Td>₯</Td>
          </Tr>
          <Tr>
            <Td>₰</Td>
            <Td>₱</Td>
            <Td>₲</Td>
            <Td>₳</Td>
            <Td>₴</Td>
            <Td>₵</Td>
            <Td>₶</Td>
            <Td>₷</Td>
            <Td>₸</Td>
            <Td>₹</Td>
            <Td>₺</Td>
            <Td>₻</Td>
            <Td>₼</Td>
            <Td>₽</Td>
            <Td>₾</Td>
            <Td>₿</Td>
          </Tr>
          <Tr>
            <Td>⃀</Td>
            <Td>⃁</Td>
            <Td>⃂</Td>
            <Td>⃃</Td>
            <Td>⃄</Td>
            <Td>⃅</Td>
            <Td>⃆</Td>
            <Td>⃇</Td>
            <Td>⃈</Td>
            <Td>⃉</Td>
            <Td>⃊</Td>
            <Td>⃋</Td>
            <Td>⃌</Td>
            <Td>⃍</Td>
            <Td>⃎</Td>
            <Td>⃏</Td>
          </Tr>
          <Tr>
            <Td>⃐</Td>
            <Td>⃑</Td>
            <Td>⃒</Td>
            <Td>⃓</Td>
            <Td>⃔</Td>
            <Td>⃕</Td>
            <Td>⃖</Td>
            <Td>⃗</Td>
            <Td>⃘</Td>
            <Td>⃙</Td>
            <Td>⃚</Td>
            <Td>⃛</Td>
            <Td>⃜</Td>
            <Td>⃝</Td>
            <Td>⃞</Td>
            <Td>⃟</Td>
          </Tr>
          <Tr>
            <Td>⃠</Td>
            <Td>⃡</Td>
            <Td>⃢</Td>
            <Td>⃣</Td>
            <Td>⃤</Td>
            <Td>⃥</Td>
            <Td>⃦</Td>
            <Td>⃧</Td>
            <Td>⃨</Td>
            <Td>⃩</Td>
            <Td>⃪</Td>
            <Td>⃫</Td>
            <Td>⃬</Td>
            <Td>⃭</Td>
            <Td>⃮</Td>
            <Td>⃯</Td>
          </Tr>
          <Tr>
            <Td>⃰</Td>
            <Td>⃱</Td>
            <Td>⃲</Td>
            <Td>⃳</Td>
            <Td>⃴</Td>
            <Td>⃵</Td>
            <Td>⃶</Td>
            <Td>⃷</Td>
            <Td>⃸</Td>
            <Td>⃹</Td>
            <Td>⃺</Td>
            <Td>⃻</Td>
            <Td>⃼</Td>
            <Td>⃽</Td>
            <Td>⃾</Td>
            <Td>⃿</Td>
          </Tr>
          <Tr>
            <Td>℀</Td>
            <Td>℁</Td>
            <Td>ℂ</Td>
            <Td>℃</Td>
            <Td>℄</Td>
            <Td>℅</Td>
            <Td>℆</Td>
            <Td>ℇ</Td>
            <Td>℈</Td>
            <Td>℉</Td>
            <Td>ℊ</Td>
            <Td>ℋ</Td>
            <Td>ℌ</Td>
            <Td>ℍ</Td>
            <Td>ℎ</Td>
            <Td>ℏ</Td>
          </Tr>
          <Tr>
            <Td>ℐ</Td>
            <Td>ℑ</Td>
            <Td>ℒ</Td>
            <Td>ℓ</Td>
            <Td>℔</Td>
            <Td>ℕ</Td>
            <Td>№</Td>
            <Td>℗</Td>
            <Td>℘</Td>
            <Td>ℙ</Td>
            <Td>ℚ</Td>
            <Td>ℛ</Td>
            <Td>ℜ</Td>
            <Td>ℝ</Td>
            <Td>℞</Td>
            <Td>℟</Td>
          </Tr>
          <Tr>
            <Td>℠</Td>
            <Td>℡</Td>
            <Td>™</Td>
            <Td>℣</Td>
            <Td>ℤ</Td>
            <Td>℥</Td>
            <Td>Ω</Td>
            <Td>℧</Td>
            <Td>ℨ</Td>
            <Td>℩</Td>
            <Td>K</Td>
            <Td>Å</Td>
            <Td>ℬ</Td>
            <Td>ℭ</Td>
            <Td>℮</Td>
            <Td>ℯ</Td>
          </Tr>
          <Tr>
            <Td>ℰ</Td>
            <Td>ℱ</Td>
            <Td>Ⅎ</Td>
            <Td>ℳ</Td>
            <Td>ℴ</Td>
            <Td>ℵ</Td>
            <Td>ℶ</Td>
            <Td>ℷ</Td>
            <Td>ℸ</Td>
            <Td>ℹ</Td>
            <Td>℺</Td>
            <Td>℻</Td>
            <Td>ℼ</Td>
            <Td>ℽ</Td>
            <Td>ℾ</Td>
            <Td>ℿ</Td>
          </Tr>
          <Tr>
            <Td>⅀</Td>
            <Td>⅁</Td>
            <Td>⅂</Td>
            <Td>⅃</Td>
            <Td>⅄</Td>
            <Td>ⅅ</Td>
            <Td>ⅆ</Td>
            <Td>ⅇ</Td>
            <Td>ⅈ</Td>
            <Td>ⅉ</Td>
            <Td>⅊</Td>
            <Td>⅋</Td>
            <Td>⅌</Td>
            <Td>⅍</Td>
            <Td>ⅎ</Td>
            <Td>⅏</Td>
          </Tr>
          <Tr>
            <Td>⅐</Td>
            <Td>⅑</Td>
            <Td>⅒</Td>
            <Td>⅓</Td>
            <Td>⅔</Td>
            <Td>⅕</Td>
            <Td>⅖</Td>
            <Td>⅗</Td>
            <Td>⅘</Td>
            <Td>⅙</Td>
            <Td>⅚</Td>
            <Td>⅛</Td>
            <Td>⅜</Td>
            <Td>⅝</Td>
            <Td>⅞</Td>
            <Td>⅟</Td>
          </Tr>
          <Tr>
            <Td>Ⅰ</Td>
            <Td>Ⅱ</Td>
            <Td>Ⅲ</Td>
            <Td>Ⅳ</Td>
            <Td>Ⅴ</Td>
            <Td>Ⅵ</Td>
            <Td>Ⅶ</Td>
            <Td>Ⅷ</Td>
            <Td>Ⅸ</Td>
            <Td>Ⅹ</Td>
            <Td>Ⅺ</Td>
            <Td>Ⅻ</Td>
            <Td>Ⅼ</Td>
            <Td>Ⅽ</Td>
            <Td>Ⅾ</Td>
            <Td>Ⅿ</Td>
          </Tr>
          <Tr>
            <Td>ⅰ</Td>
            <Td>ⅱ</Td>
            <Td>ⅲ</Td>
            <Td>ⅳ</Td>
            <Td>ⅴ</Td>
            <Td>ⅵ</Td>
            <Td>ⅶ</Td>
            <Td>ⅷ</Td>
            <Td>ⅸ</Td>
            <Td>ⅹ</Td>
            <Td>ⅺ</Td>
            <Td>ⅻ</Td>
            <Td>ⅼ</Td>
            <Td>ⅽ</Td>
            <Td>ⅾ</Td>
            <Td>ⅿ</Td>
          </Tr>
          <Tr>
            <Td>ↀ</Td>
            <Td>ↁ</Td>
            <Td>ↂ</Td>
            <Td>Ↄ</Td>
            <Td>ↄ</Td>
            <Td>ↅ</Td>
            <Td>ↆ</Td>
            <Td>ↇ</Td>
            <Td>ↈ</Td>
            <Td>↉</Td>
            <Td>↊</Td>
            <Td>↋</Td>
            <Td>↌</Td>
            <Td>↍</Td>
            <Td>↎</Td>
            <Td>↏</Td>
          </Tr>
          <Tr>
            <Td>←</Td>
            <Td>↑</Td>
            <Td>→</Td>
            <Td>↓</Td>
            <Td>↔</Td>
            <Td>↕</Td>
            <Td>↖</Td>
            <Td>↗</Td>
            <Td>↘</Td>
            <Td>↙</Td>
            <Td>↚</Td>
            <Td>↛</Td>
            <Td>↜</Td>
            <Td>↝</Td>
            <Td>↞</Td>
            <Td>↟</Td>
          </Tr>
          <Tr>
            <Td>↠</Td>
            <Td>↡</Td>
            <Td>↢</Td>
            <Td>↣</Td>
            <Td>↤</Td>
            <Td>↥</Td>
            <Td>↦</Td>
            <Td>↧</Td>
            <Td>↨</Td>
            <Td>↩</Td>
            <Td>↪</Td>
            <Td>↫</Td>
            <Td>↬</Td>
            <Td>↭</Td>
            <Td>↮</Td>
            <Td>↯</Td>
          </Tr>
          <Tr>
            <Td>↰</Td>
            <Td>↱</Td>
            <Td>↲</Td>
            <Td>↳</Td>
            <Td>↴</Td>
            <Td>↵</Td>
            <Td>↶</Td>
            <Td>↷</Td>
            <Td>↸</Td>
            <Td>↹</Td>
            <Td>↺</Td>
            <Td>↻</Td>
            <Td>↼</Td>
            <Td>↽</Td>
            <Td>↾</Td>
            <Td>↿</Td>
          </Tr>
          <Tr>
            <Td>⇀</Td>
            <Td>⇁</Td>
            <Td>⇂</Td>
            <Td>⇃</Td>
            <Td>⇄</Td>
            <Td>⇅</Td>
            <Td>⇆</Td>
            <Td>⇇</Td>
            <Td>⇈</Td>
            <Td>⇉</Td>
            <Td>⇊</Td>
            <Td>⇋</Td>
            <Td>⇌</Td>
            <Td>⇍</Td>
            <Td>⇎</Td>
            <Td>⇏</Td>
          </Tr>
          <Tr>
            <Td>⇐</Td>
            <Td>⇑</Td>
            <Td>⇒</Td>
            <Td>⇓</Td>
            <Td>⇔</Td>
            <Td>⇕</Td>
            <Td>⇖</Td>
            <Td>⇗</Td>
            <Td>⇘</Td>
            <Td>⇙</Td>
            <Td>⇚</Td>
            <Td>⇛</Td>
            <Td>⇜</Td>
            <Td>⇝</Td>
            <Td>⇞</Td>
            <Td>⇟</Td>
          </Tr>
          <Tr>
            <Td>⇠</Td>
            <Td>⇡</Td>
            <Td>⇢</Td>
            <Td>⇣</Td>
            <Td>⇤</Td>
            <Td>⇥</Td>
            <Td>⇦</Td>
            <Td>⇧</Td>
            <Td>⇨</Td>
            <Td>⇩</Td>
            <Td>⇪</Td>
            <Td>⇫</Td>
            <Td>⇬</Td>
            <Td>⇭</Td>
            <Td>⇮</Td>
            <Td>⇯</Td>
          </Tr>
          <Tr>
            <Td>⇰</Td>
            <Td>⇱</Td>
            <Td>⇲</Td>
            <Td>⇳</Td>
            <Td>⇴</Td>
            <Td>⇵</Td>
            <Td>⇶</Td>
            <Td>⇷</Td>
            <Td>⇸</Td>
            <Td>⇹</Td>
            <Td>⇺</Td>
            <Td>⇻</Td>
            <Td>⇼</Td>
            <Td>⇽</Td>
            <Td>⇾</Td>
            <Td>⇿</Td>
          </Tr>
          <Tr>
            <Td>0</Td>
            <Td>1</Td>
            <Td>2</Td>
            <Td>3</Td>
            <Td>4</Td>
            <Td>5</Td>
            <Td>6</Td>
            <Td>7</Td>
            <Td>8</Td>
            <Td>9</Td>
            <Td>a</Td>
            <Td>b</Td>
            <Td>c</Td>
            <Td>d</Td>
            <Td>e</Td>
            <Td>f</Td>
          </Tr>
          <Tr>
            <Td>∀</Td>
            <Td>∁</Td>
            <Td>∂</Td>
            <Td>∃</Td>
            <Td>∄</Td>
            <Td>∅</Td>
            <Td>∆</Td>
            <Td>∇</Td>
            <Td>∈</Td>
            <Td>∉</Td>
            <Td>∊</Td>
            <Td>∋</Td>
            <Td>∌</Td>
            <Td>∍</Td>
            <Td>∎</Td>
            <Td>∏</Td>
          </Tr>
          <Tr>
            <Td>∐</Td>
            <Td>∑</Td>
            <Td>−</Td>
            <Td>∓</Td>
            <Td>∔</Td>
            <Td>∕</Td>
            <Td>∖</Td>
            <Td>∗</Td>
            <Td>∘</Td>
            <Td>∙</Td>
            <Td>√</Td>
            <Td>∛</Td>
            <Td>∜</Td>
            <Td>∝</Td>
            <Td>∞</Td>
            <Td>∟</Td>
          </Tr>
          <Tr>
            <Td>∠</Td>
            <Td>∡</Td>
            <Td>∢</Td>
            <Td>∣</Td>
            <Td>∤</Td>
            <Td>∥</Td>
            <Td>∦</Td>
            <Td>∧</Td>
            <Td>∨</Td>
            <Td>∩</Td>
            <Td>∪</Td>
            <Td>∫</Td>
            <Td>∬</Td>
            <Td>∭</Td>
            <Td>∮</Td>
            <Td>∯</Td>
          </Tr>
          <Tr>
            <Td>∰</Td>
            <Td>∱</Td>
            <Td>∲</Td>
            <Td>∳</Td>
            <Td>∴</Td>
            <Td>∵</Td>
            <Td>∶</Td>
            <Td>∷</Td>
            <Td>∸</Td>
            <Td>∹</Td>
            <Td>∺</Td>
            <Td>∻</Td>
            <Td>∼</Td>
            <Td>∽</Td>
            <Td>∾</Td>
            <Td>∿</Td>
          </Tr>
          <Tr>
            <Td>≀</Td>
            <Td>≁</Td>
            <Td>≂</Td>
            <Td>≃</Td>
            <Td>≄</Td>
            <Td>≅</Td>
            <Td>≆</Td>
            <Td>≇</Td>
            <Td>≈</Td>
            <Td>≉</Td>
            <Td>≊</Td>
            <Td>≋</Td>
            <Td>≌</Td>
            <Td>≍</Td>
            <Td>≎</Td>
            <Td>≏</Td>
          </Tr>
          <Tr>
            <Td>≐</Td>
            <Td>≑</Td>
            <Td>≒</Td>
            <Td>≓</Td>
            <Td>≔</Td>
            <Td>≕</Td>
            <Td>≖</Td>
            <Td>≗</Td>
            <Td>≘</Td>
            <Td>≙</Td>
            <Td>≚</Td>
            <Td>≛</Td>
            <Td>≜</Td>
            <Td>≝</Td>
            <Td>≞</Td>
            <Td>≟</Td>
          </Tr>
          <Tr>
            <Td>≠</Td>
            <Td>≡</Td>
            <Td>≢</Td>
            <Td>≣</Td>
            <Td>≤</Td>
            <Td>≥</Td>
            <Td>≦</Td>
            <Td>≧</Td>
            <Td>≨</Td>
            <Td>≩</Td>
            <Td>≪</Td>
            <Td>≫</Td>
            <Td>≬</Td>
            <Td>≭</Td>
            <Td>≮</Td>
            <Td>≯</Td>
          </Tr>
          <Tr>
            <Td>≰</Td>
            <Td>≱</Td>
            <Td>≲</Td>
            <Td>≳</Td>
            <Td>≴</Td>
            <Td>≵</Td>
            <Td>≶</Td>
            <Td>≷</Td>
            <Td>≸</Td>
            <Td>≹</Td>
            <Td>≺</Td>
            <Td>≻</Td>
            <Td>≼</Td>
            <Td>≽</Td>
            <Td>≾</Td>
            <Td>≿</Td>
          </Tr>
          <Tr>
            <Td>⊀</Td>
            <Td>⊁</Td>
            <Td>⊂</Td>
            <Td>⊃</Td>
            <Td>⊄</Td>
            <Td>⊅</Td>
            <Td>⊆</Td>
            <Td>⊇</Td>
            <Td>⊈</Td>
            <Td>⊉</Td>
            <Td>⊊</Td>
            <Td>⊋</Td>
            <Td>⊌</Td>
            <Td>⊍</Td>
            <Td>⊎</Td>
            <Td>⊏</Td>
          </Tr>
          <Tr>
            <Td>⊐</Td>
            <Td>⊑</Td>
            <Td>⊒</Td>
            <Td>⊓</Td>
            <Td>⊔</Td>
            <Td>⊕</Td>
            <Td>⊖</Td>
            <Td>⊗</Td>
            <Td>⊘</Td>
            <Td>⊙</Td>
            <Td>⊚</Td>
            <Td>⊛</Td>
            <Td>⊜</Td>
            <Td>⊝</Td>
            <Td>⊞</Td>
            <Td>⊟</Td>
          </Tr>
          <Tr>
            <Td>⊠</Td>
            <Td>⊡</Td>
            <Td>⊢</Td>
            <Td>⊣</Td>
            <Td>⊤</Td>
            <Td>⊥</Td>
            <Td>⊦</Td>
            <Td>⊧</Td>
            <Td>⊨</Td>
            <Td>⊩</Td>
            <Td>⊪</Td>
            <Td>⊫</Td>
            <Td>⊬</Td>
            <Td>⊭</Td>
            <Td>⊮</Td>
            <Td>⊯</Td>
          </Tr>
          <Tr>
            <Td>⊰</Td>
            <Td>⊱</Td>
            <Td>⊲</Td>
            <Td>⊳</Td>
            <Td>⊴</Td>
            <Td>⊵</Td>
            <Td>⊶</Td>
            <Td>⊷</Td>
            <Td>⊸</Td>
            <Td>⊹</Td>
            <Td>⊺</Td>
            <Td>⊻</Td>
            <Td>⊼</Td>
            <Td>⊽</Td>
            <Td>⊾</Td>
            <Td>⊿</Td>
          </Tr>
          <Tr>
            <Td>⋀</Td>
            <Td>⋁</Td>
            <Td>⋂</Td>
            <Td>⋃</Td>
            <Td>⋄</Td>
            <Td>⋅</Td>
            <Td>⋆</Td>
            <Td>⋇</Td>
            <Td>⋈</Td>
            <Td>⋉</Td>
            <Td>⋊</Td>
            <Td>⋋</Td>
            <Td>⋌</Td>
            <Td>⋍</Td>
            <Td>⋎</Td>
            <Td>⋏</Td>
          </Tr>
          <Tr>
            <Td>⋐</Td>
            <Td>⋑</Td>
            <Td>⋒</Td>
            <Td>⋓</Td>
            <Td>⋔</Td>
            <Td>⋕</Td>
            <Td>⋖</Td>
            <Td>⋗</Td>
            <Td>⋘</Td>
            <Td>⋙</Td>
            <Td>⋚</Td>
            <Td>⋛</Td>
            <Td>⋜</Td>
            <Td>⋝</Td>
            <Td>⋞</Td>
            <Td>⋟</Td>
          </Tr>
          <Tr>
            <Td>⋠</Td>
            <Td>⋡</Td>
            <Td>⋢</Td>
            <Td>⋣</Td>
            <Td>⋤</Td>
            <Td>⋥</Td>
            <Td>⋦</Td>
            <Td>⋧</Td>
            <Td>⋨</Td>
            <Td>⋩</Td>
            <Td>⋪</Td>
            <Td>⋫</Td>
            <Td>⋬</Td>
            <Td>⋭</Td>
            <Td>⋮</Td>
            <Td>⋯</Td>
          </Tr>
          <Tr>
            <Td>⋰</Td>
            <Td>⋱</Td>
            <Td>⋲</Td>
            <Td>⋳</Td>
            <Td>⋴</Td>
            <Td>⋵</Td>
            <Td>⋶</Td>
            <Td>⋷</Td>
            <Td>⋸</Td>
            <Td>⋹</Td>
            <Td>⋺</Td>
            <Td>⋻</Td>
            <Td>⋼</Td>
            <Td>⋽</Td>
            <Td>⋾</Td>
            <Td>⋿</Td>
          </Tr>
          <Tr>
            <Td>⌀</Td>
            <Td>⌁</Td>
            <Td>⌂</Td>
            <Td>⌃</Td>
            <Td>⌄</Td>
            <Td>⌅</Td>
            <Td>⌆</Td>
            <Td>⌇</Td>
            <Td>⌈</Td>
            <Td>⌉</Td>
            <Td>⌊</Td>
            <Td>⌋</Td>
            <Td>⌌</Td>
            <Td>⌍</Td>
            <Td>⌎</Td>
            <Td>⌏</Td>
          </Tr>
          <Tr>
            <Td>⌐</Td>
            <Td>⌑</Td>
            <Td>⌒</Td>
            <Td>⌓</Td>
            <Td>⌔</Td>
            <Td>⌕</Td>
            <Td>⌖</Td>
            <Td>⌗</Td>
            <Td>⌘</Td>
            <Td>⌙</Td>
            <Td>⌚</Td>
            <Td>⌛</Td>
            <Td>⌜</Td>
            <Td>⌝</Td>
            <Td>⌞</Td>
            <Td>⌟</Td>
          </Tr>
          <Tr>
            <Td>⌠</Td>
            <Td>⌡</Td>
            <Td>⌢</Td>
            <Td>⌣</Td>
            <Td>⌤</Td>
            <Td>⌥</Td>
            <Td>⌦</Td>
            <Td>⌧</Td>
            <Td>⌨</Td>
            <Td>〈</Td>
            <Td>〉</Td>
            <Td>⌫</Td>
            <Td>⌬</Td>
            <Td>⌭</Td>
            <Td>⌮</Td>
            <Td>⌯</Td>
          </Tr>
          <Tr>
            <Td>⌰</Td>
            <Td>⌱</Td>
            <Td>⌲</Td>
            <Td>⌳</Td>
            <Td>⌴</Td>
            <Td>⌵</Td>
            <Td>⌶</Td>
            <Td>⌷</Td>
            <Td>⌸</Td>
            <Td>⌹</Td>
            <Td>⌺</Td>
            <Td>⌻</Td>
            <Td>⌼</Td>
            <Td>⌽</Td>
            <Td>⌾</Td>
            <Td>⌿</Td>
          </Tr>
          <Tr>
            <Td>⍀</Td>
            <Td>⍁</Td>
            <Td>⍂</Td>
            <Td>⍃</Td>
            <Td>⍄</Td>
            <Td>⍅</Td>
            <Td>⍆</Td>
            <Td>⍇</Td>
            <Td>⍈</Td>
            <Td>⍉</Td>
            <Td>⍊</Td>
            <Td>⍋</Td>
            <Td>⍌</Td>
            <Td>⍍</Td>
            <Td>⍎</Td>
            <Td>⍏</Td>
          </Tr>
          <Tr>
            <Td>⍐</Td>
            <Td>⍑</Td>
            <Td>⍒</Td>
            <Td>⍓</Td>
            <Td>⍔</Td>
            <Td>⍕</Td>
            <Td>⍖</Td>
            <Td>⍗</Td>
            <Td>⍘</Td>
            <Td>⍙</Td>
            <Td>⍚</Td>
            <Td>⍛</Td>
            <Td>⍜</Td>
            <Td>⍝</Td>
            <Td>⍞</Td>
            <Td>⍟</Td>
          </Tr>
          <Tr>
            <Td>⍠</Td>
            <Td>⍡</Td>
            <Td>⍢</Td>
            <Td>⍣</Td>
            <Td>⍤</Td>
            <Td>⍥</Td>
            <Td>⍦</Td>
            <Td>⍧</Td>
            <Td>⍨</Td>
            <Td>⍩</Td>
            <Td>⍪</Td>
            <Td>⍫</Td>
            <Td>⍬</Td>
            <Td>⍭</Td>
            <Td>⍮</Td>
            <Td>⍯</Td>
          </Tr>
          <Tr>
            <Td>⍰</Td>
            <Td>⍱</Td>
            <Td>⍲</Td>
            <Td>⍳</Td>
            <Td>⍴</Td>
            <Td>⍵</Td>
            <Td>⍶</Td>
            <Td>⍷</Td>
            <Td>⍸</Td>
            <Td>⍹</Td>
            <Td>⍺</Td>
            <Td>⍻</Td>
            <Td>⍼</Td>
            <Td>⍽</Td>
            <Td>⍾</Td>
            <Td>⍿</Td>
          </Tr>
          <Tr>
            <Td>⎀</Td>
            <Td>⎁</Td>
            <Td>⎂</Td>
            <Td>⎃</Td>
            <Td>⎄</Td>
            <Td>⎅</Td>
            <Td>⎆</Td>
            <Td>⎇</Td>
            <Td>⎈</Td>
            <Td>⎉</Td>
            <Td>⎊</Td>
            <Td>⎋</Td>
            <Td>⎌</Td>
            <Td>⎍</Td>
            <Td>⎎</Td>
            <Td>⎏</Td>
          </Tr>
          <Tr>
            <Td>⎐</Td>
            <Td>⎑</Td>
            <Td>⎒</Td>
            <Td>⎓</Td>
            <Td>⎔</Td>
            <Td>⎕</Td>
            <Td>⎖</Td>
            <Td>⎗</Td>
            <Td>⎘</Td>
            <Td>⎙</Td>
            <Td>⎚</Td>
            <Td>⎛</Td>
            <Td>⎜</Td>
            <Td>⎝</Td>
            <Td>⎞</Td>
            <Td>⎟</Td>
          </Tr>
          <Tr>
            <Td>⎠</Td>
            <Td>⎡</Td>
            <Td>⎢</Td>
            <Td>⎣</Td>
            <Td>⎤</Td>
            <Td>⎥</Td>
            <Td>⎦</Td>
            <Td>⎧</Td>
            <Td>⎨</Td>
            <Td>⎩</Td>
            <Td>⎪</Td>
            <Td>⎫</Td>
            <Td>⎬</Td>
            <Td>⎭</Td>
            <Td>⎮</Td>
            <Td>⎯</Td>
          </Tr>
          <Tr>
            <Td>⎰</Td>
            <Td>⎱</Td>
            <Td>⎲</Td>
            <Td>⎳</Td>
            <Td>⎴</Td>
            <Td>⎵</Td>
            <Td>⎶</Td>
            <Td>⎷</Td>
            <Td>⎸</Td>
            <Td>⎹</Td>
            <Td>⎺</Td>
            <Td>⎻</Td>
            <Td>⎼</Td>
            <Td>⎽</Td>
            <Td>⎾</Td>
            <Td>⎿</Td>
          </Tr>
          <Tr>
            <Td>⏀</Td>
            <Td>⏁</Td>
            <Td>⏂</Td>
            <Td>⏃</Td>
            <Td>⏄</Td>
            <Td>⏅</Td>
            <Td>⏆</Td>
            <Td>⏇</Td>
            <Td>⏈</Td>
            <Td>⏉</Td>
            <Td>⏊</Td>
            <Td>⏋</Td>
            <Td>⏌</Td>
            <Td>⏍</Td>
            <Td>⏎</Td>
            <Td>⏏</Td>
          </Tr>
          <Tr>
            <Td>⏐</Td>
            <Td>⏑</Td>
            <Td>⏒</Td>
            <Td>⏓</Td>
            <Td>⏔</Td>
            <Td>⏕</Td>
            <Td>⏖</Td>
            <Td>⏗</Td>
            <Td>⏘</Td>
            <Td>⏙</Td>
            <Td>⏚</Td>
            <Td>⏛</Td>
            <Td>⏜</Td>
            <Td>⏝</Td>
            <Td>⏞</Td>
            <Td>⏟</Td>
          </Tr>
          <Tr>
            <Td>⏠</Td>
            <Td>⏡</Td>
            <Td>⏢</Td>
            <Td>⏣</Td>
            <Td>⏤</Td>
            <Td>⏥</Td>
            <Td>⏦</Td>
            <Td>⏧</Td>
            <Td>⏨</Td>
            <Td>⏩</Td>
            <Td>⏪</Td>
            <Td>⏫</Td>
            <Td>⏬</Td>
            <Td>⏭</Td>
            <Td>⏮</Td>
            <Td>⏯</Td>
          </Tr>
          <Tr>
            <Td>⏰</Td>
            <Td>⏱</Td>
            <Td>⏲</Td>
            <Td>⏳</Td>
            <Td>⏴</Td>
            <Td>⏵</Td>
            <Td>⏶</Td>
            <Td>⏷</Td>
            <Td>⏸</Td>
            <Td>⏹</Td>
            <Td>⏺</Td>
            <Td>⏻</Td>
            <Td>⏼</Td>
            <Td>⏽</Td>
            <Td>⏾</Td>
            <Td>⏿</Td>
          </Tr>
          <Tr>
            <Td>0</Td>
            <Td>1</Td>
            <Td>2</Td>
            <Td>3</Td>
            <Td>4</Td>
            <Td>5</Td>
            <Td>6</Td>
            <Td>7</Td>
            <Td>8</Td>
            <Td>9</Td>
            <Td>a</Td>
            <Td>b</Td>
            <Td>c</Td>
            <Td>d</Td>
            <Td>e</Td>
            <Td>f</Td>
          </Tr>
          <Tr>
            <Td>␀</Td>
            <Td>␁</Td>
            <Td>␂</Td>
            <Td>␃</Td>
            <Td>␄</Td>
            <Td>␅</Td>
            <Td>␆</Td>
            <Td>␇</Td>
            <Td>␈</Td>
            <Td>␉</Td>
            <Td>␊</Td>
            <Td>␋</Td>
            <Td>␌</Td>
            <Td>␍</Td>
            <Td>␎</Td>
            <Td>␏</Td>
          </Tr>
          <Tr>
            <Td>␐</Td>
            <Td>␑</Td>
            <Td>␒</Td>
            <Td>␓</Td>
            <Td>␔</Td>
            <Td>␕</Td>
            <Td>␖</Td>
            <Td>␗</Td>
            <Td>␘</Td>
            <Td>␙</Td>
            <Td>␚</Td>
            <Td>␛</Td>
            <Td>␜</Td>
            <Td>␝</Td>
            <Td>␞</Td>
            <Td>␟</Td>
          </Tr>
          <Tr>
            <Td>␠</Td>
            <Td>␡</Td>
            <Td>␢</Td>
            <Td>␣</Td>
            <Td>␤</Td>
            <Td>␥</Td>
            <Td>␦</Td>
            <Td>␧</Td>
            <Td>␨</Td>
            <Td>␩</Td>
            <Td>␪</Td>
            <Td>␫</Td>
            <Td>␬</Td>
            <Td>␭</Td>
            <Td>␮</Td>
            <Td>␯</Td>
          </Tr>
          <Tr>
            <Td>␰</Td>
            <Td>␱</Td>
            <Td>␲</Td>
            <Td>␳</Td>
            <Td>␴</Td>
            <Td>␵</Td>
            <Td>␶</Td>
            <Td>␷</Td>
            <Td>␸</Td>
            <Td>␹</Td>
            <Td>␺</Td>
            <Td>␻</Td>
            <Td>␼</Td>
            <Td>␽</Td>
            <Td>␾</Td>
            <Td>␿</Td>
          </Tr>
          <Tr>
            <Td>⑀</Td>
            <Td>⑁</Td>
            <Td>⑂</Td>
            <Td>⑃</Td>
            <Td>⑄</Td>
            <Td>⑅</Td>
            <Td>⑆</Td>
            <Td>⑇</Td>
            <Td>⑈</Td>
            <Td>⑉</Td>
            <Td>⑊</Td>
            <Td>⑋</Td>
            <Td>⑌</Td>
            <Td>⑍</Td>
            <Td>⑎</Td>
            <Td>⑏</Td>
          </Tr>
          <Tr>
            <Td>⑐</Td>
            <Td>⑑</Td>
            <Td>⑒</Td>
            <Td>⑓</Td>
            <Td>⑔</Td>
            <Td>⑕</Td>
            <Td>⑖</Td>
            <Td>⑗</Td>
            <Td>⑘</Td>
            <Td>⑙</Td>
            <Td>⑚</Td>
            <Td>⑛</Td>
            <Td>⑜</Td>
            <Td>⑝</Td>
            <Td>⑞</Td>
            <Td>⑟</Td>
          </Tr>
          <Tr>
            <Td>①</Td>
            <Td>②</Td>
            <Td>③</Td>
            <Td>④</Td>
            <Td>⑤</Td>
            <Td>⑥</Td>
            <Td>⑦</Td>
            <Td>⑧</Td>
            <Td>⑨</Td>
            <Td>⑩</Td>
            <Td>⑪</Td>
            <Td>⑫</Td>
            <Td>⑬</Td>
            <Td>⑭</Td>
            <Td>⑮</Td>
            <Td>⑯</Td>
          </Tr>
          <Tr>
            <Td>⑰</Td>
            <Td>⑱</Td>
            <Td>⑲</Td>
            <Td>⑳</Td>
            <Td>⑴</Td>
            <Td>⑵</Td>
            <Td>⑶</Td>
            <Td>⑷</Td>
            <Td>⑸</Td>
            <Td>⑹</Td>
            <Td>⑺</Td>
            <Td>⑻</Td>
            <Td>⑼</Td>
            <Td>⑽</Td>
            <Td>⑾</Td>
            <Td>⑿</Td>
          </Tr>
          <Tr>
            <Td>⒀</Td>
            <Td>⒁</Td>
            <Td>⒂</Td>
            <Td>⒃</Td>
            <Td>⒄</Td>
            <Td>⒅</Td>
            <Td>⒆</Td>
            <Td>⒇</Td>
            <Td>⒈</Td>
            <Td>⒉</Td>
            <Td>⒊</Td>
            <Td>⒋</Td>
            <Td>⒌</Td>
            <Td>⒍</Td>
            <Td>⒎</Td>
            <Td>⒏</Td>
          </Tr>
          <Tr>
            <Td>⒐</Td>
            <Td>⒑</Td>
            <Td>⒒</Td>
            <Td>⒓</Td>
            <Td>⒔</Td>
            <Td>⒕</Td>
            <Td>⒖</Td>
            <Td>⒗</Td>
            <Td>⒘</Td>
            <Td>⒙</Td>
            <Td>⒚</Td>
            <Td>⒛</Td>
            <Td>⒜</Td>
            <Td>⒝</Td>
            <Td>⒞</Td>
            <Td>⒟</Td>
          </Tr>
          <Tr>
            <Td>⒠</Td>
            <Td>⒡</Td>
            <Td>⒢</Td>
            <Td>⒣</Td>
            <Td>⒤</Td>
            <Td>⒥</Td>
            <Td>⒦</Td>
            <Td>⒧</Td>
            <Td>⒨</Td>
            <Td>⒩</Td>
            <Td>⒪</Td>
            <Td>⒫</Td>
            <Td>⒬</Td>
            <Td>⒭</Td>
            <Td>⒮</Td>
            <Td>⒯</Td>
          </Tr>
          <Tr>
            <Td>⒰</Td>
            <Td>⒱</Td>
            <Td>⒲</Td>
            <Td>⒳</Td>
            <Td>⒴</Td>
            <Td>⒵</Td>
            <Td>Ⓐ</Td>
            <Td>Ⓑ</Td>
            <Td>Ⓒ</Td>
            <Td>Ⓓ</Td>
            <Td>Ⓔ</Td>
            <Td>Ⓕ</Td>
            <Td>Ⓖ</Td>
            <Td>Ⓗ</Td>
            <Td>Ⓘ</Td>
            <Td>Ⓙ</Td>
          </Tr>
          <Tr>
            <Td>Ⓚ</Td>
            <Td>Ⓛ</Td>
            <Td>Ⓜ</Td>
            <Td>Ⓝ</Td>
            <Td>Ⓞ</Td>
            <Td>Ⓟ</Td>
            <Td>Ⓠ</Td>
            <Td>Ⓡ</Td>
            <Td>Ⓢ</Td>
            <Td>Ⓣ</Td>
            <Td>Ⓤ</Td>
            <Td>Ⓥ</Td>
            <Td>Ⓦ</Td>
            <Td>Ⓧ</Td>
            <Td>Ⓨ</Td>
            <Td>Ⓩ</Td>
          </Tr>
          <Tr>
            <Td>ⓐ</Td>
            <Td>ⓑ</Td>
            <Td>ⓒ</Td>
            <Td>ⓓ</Td>
            <Td>ⓔ</Td>
            <Td>ⓕ</Td>
            <Td>ⓖ</Td>
            <Td>ⓗ</Td>
            <Td>ⓘ</Td>
            <Td>ⓙ</Td>
            <Td>ⓚ</Td>
            <Td>ⓛ</Td>
            <Td>ⓜ</Td>
            <Td>ⓝ</Td>
            <Td>ⓞ</Td>
            <Td>ⓟ</Td>
          </Tr>
          <Tr>
            <Td>ⓠ</Td>
            <Td>ⓡ</Td>
            <Td>ⓢ</Td>
            <Td>ⓣ</Td>
            <Td>ⓤ</Td>
            <Td>ⓥ</Td>
            <Td>ⓦ</Td>
            <Td>ⓧ</Td>
            <Td>ⓨ</Td>
            <Td>ⓩ</Td>
            <Td>⓪</Td>
            <Td>⓫</Td>
            <Td>⓬</Td>
            <Td>⓭</Td>
            <Td>⓮</Td>
            <Td>⓯</Td>
          </Tr>
          <Tr>
            <Td>⓰</Td>
            <Td>⓱</Td>
            <Td>⓲</Td>
            <Td>⓳</Td>
            <Td>⓴</Td>
            <Td>⓵</Td>
            <Td>⓶</Td>
            <Td>⓷</Td>
            <Td>⓸</Td>
            <Td>⓹</Td>
            <Td>⓺</Td>
            <Td>⓻</Td>
            <Td>⓼</Td>
            <Td>⓽</Td>
            <Td>⓾</Td>
            <Td>⓿</Td>
          </Tr>
          <Tr>
            <Td>─</Td>
            <Td>━</Td>
            <Td>│</Td>
            <Td>┃</Td>
            <Td>┄</Td>
            <Td>┅</Td>
            <Td>┆</Td>
            <Td>┇</Td>
            <Td>┈</Td>
            <Td>┉</Td>
            <Td>┊</Td>
            <Td>┋</Td>
            <Td>┌</Td>
            <Td>┍</Td>
            <Td>┎</Td>
            <Td>┏</Td>
          </Tr>
          <Tr>
            <Td>┐</Td>
            <Td>┑</Td>
            <Td>┒</Td>
            <Td>┓</Td>
            <Td>└</Td>
            <Td>┕</Td>
            <Td>┖</Td>
            <Td>┗</Td>
            <Td>┘</Td>
            <Td>┙</Td>
            <Td>┚</Td>
            <Td>┛</Td>
            <Td>├</Td>
            <Td>┝</Td>
            <Td>┞</Td>
            <Td>┟</Td>
          </Tr>
          <Tr>
            <Td>┠</Td>
            <Td>┡</Td>
            <Td>┢</Td>
            <Td>┣</Td>
            <Td>┤</Td>
            <Td>┥</Td>
            <Td>┦</Td>
            <Td>┧</Td>
            <Td>┨</Td>
            <Td>┩</Td>
            <Td>┪</Td>
            <Td>┫</Td>
            <Td>┬</Td>
            <Td>┭</Td>
            <Td>┮</Td>
            <Td>┯</Td>
          </Tr>
          <Tr>
            <Td>┰</Td>
            <Td>┱</Td>
            <Td>┲</Td>
            <Td>┳</Td>
            <Td>┴</Td>
            <Td>┵</Td>
            <Td>┶</Td>
            <Td>┷</Td>
            <Td>┸</Td>
            <Td>┹</Td>
            <Td>┺</Td>
            <Td>┻</Td>
            <Td>┼</Td>
            <Td>┽</Td>
            <Td>┾</Td>
            <Td>┿</Td>
          </Tr>
          <Tr>
            <Td>╀</Td>
            <Td>╁</Td>
            <Td>╂</Td>
            <Td>╃</Td>
            <Td>╄</Td>
            <Td>╅</Td>
            <Td>╆</Td>
            <Td>╇</Td>
            <Td>╈</Td>
            <Td>╉</Td>
            <Td>╊</Td>
            <Td>╋</Td>
            <Td>╌</Td>
            <Td>╍</Td>
            <Td>╎</Td>
            <Td>╏</Td>
          </Tr>
          <Tr>
            <Td>═</Td>
            <Td>║</Td>
            <Td>╒</Td>
            <Td>╓</Td>
            <Td>╔</Td>
            <Td>╕</Td>
            <Td>╖</Td>
            <Td>╗</Td>
            <Td>╘</Td>
            <Td>╙</Td>
            <Td>╚</Td>
            <Td>╛</Td>
            <Td>╜</Td>
            <Td>╝</Td>
            <Td>╞</Td>
            <Td>╟</Td>
          </Tr>
          <Tr>
            <Td>╠</Td>
            <Td>╡</Td>
            <Td>╢</Td>
            <Td>╣</Td>
            <Td>╤</Td>
            <Td>╥</Td>
            <Td>╦</Td>
            <Td>╧</Td>
            <Td>╨</Td>
            <Td>╩</Td>
            <Td>╪</Td>
            <Td>╫</Td>
            <Td>╬</Td>
            <Td>╭</Td>
            <Td>╮</Td>
            <Td>╯</Td>
          </Tr>
          <Tr>
            <Td>╰</Td>
            <Td>╱</Td>
            <Td>╲</Td>
            <Td>╳</Td>
            <Td>╴</Td>
            <Td>╵</Td>
            <Td>╶</Td>
            <Td>╷</Td>
            <Td>╸</Td>
            <Td>╹</Td>
            <Td>╺</Td>
            <Td>╻</Td>
            <Td>╼</Td>
            <Td>╽</Td>
            <Td>╾</Td>
            <Td>╿</Td>
          </Tr>
          <Tr>
            <Td>▀</Td>
            <Td>▁</Td>
            <Td>▂</Td>
            <Td>▃</Td>
            <Td>▄</Td>
            <Td>▅</Td>
            <Td>▆</Td>
            <Td>▇</Td>
            <Td>█</Td>
            <Td>▉</Td>
            <Td>▊</Td>
            <Td>▋</Td>
            <Td>▌</Td>
            <Td>▍</Td>
            <Td>▎</Td>
            <Td>▏</Td>
          </Tr>
          <Tr>
            <Td>▐</Td>
            <Td>░</Td>
            <Td>▒</Td>
            <Td>▓</Td>
            <Td>▔</Td>
            <Td>▕</Td>
            <Td>▖</Td>
            <Td>▗</Td>
            <Td>▘</Td>
            <Td>▙</Td>
            <Td>▚</Td>
            <Td>▛</Td>
            <Td>▜</Td>
            <Td>▝</Td>
            <Td>▞</Td>
            <Td>▟</Td>
          </Tr>
          <Tr>
            <Td>■</Td>
            <Td>□</Td>
            <Td>▢</Td>
            <Td>▣</Td>
            <Td>▤</Td>
            <Td>▥</Td>
            <Td>▦</Td>
            <Td>▧</Td>
            <Td>▨</Td>
            <Td>▩</Td>
            <Td>▪</Td>
            <Td>▫</Td>
            <Td>▬</Td>
            <Td>▭</Td>
            <Td>▮</Td>
            <Td>▯</Td>
          </Tr>
          <Tr>
            <Td>▰</Td>
            <Td>▱</Td>
            <Td>▲</Td>
            <Td>△</Td>
            <Td>▴</Td>
            <Td>▵</Td>
            <Td>▶</Td>
            <Td>▷</Td>
            <Td>▸</Td>
            <Td>▹</Td>
            <Td>►</Td>
            <Td>▻</Td>
            <Td>▼</Td>
            <Td>▽</Td>
            <Td>▾</Td>
            <Td>▿</Td>
          </Tr>
          <Tr>
            <Td>◀</Td>
            <Td>◁</Td>
            <Td>◂</Td>
            <Td>◃</Td>
            <Td>◄</Td>
            <Td>◅</Td>
            <Td>◆</Td>
            <Td>◇</Td>
            <Td>◈</Td>
            <Td>◉</Td>
            <Td>◊</Td>
            <Td>○</Td>
            <Td>◌</Td>
            <Td>◍</Td>
            <Td>◎</Td>
            <Td>●</Td>
          </Tr>
          <Tr>
            <Td>◐</Td>
            <Td>◑</Td>
            <Td>◒</Td>
            <Td>◓</Td>
            <Td>◔</Td>
            <Td>◕</Td>
            <Td>◖</Td>
            <Td>◗</Td>
            <Td>◘</Td>
            <Td>◙</Td>
            <Td>◚</Td>
            <Td>◛</Td>
            <Td>◜</Td>
            <Td>◝</Td>
            <Td>◞</Td>
            <Td>◟</Td>
          </Tr>
          <Tr>
            <Td>◠</Td>
            <Td>◡</Td>
            <Td>◢</Td>
            <Td>◣</Td>
            <Td>◤</Td>
            <Td>◥</Td>
            <Td>◦</Td>
            <Td>◧</Td>
            <Td>◨</Td>
            <Td>◩</Td>
            <Td>◪</Td>
            <Td>◫</Td>
            <Td>◬</Td>
            <Td>◭</Td>
            <Td>◮</Td>
            <Td>◯</Td>
          </Tr>
          <Tr>
            <Td>◰</Td>
            <Td>◱</Td>
            <Td>◲</Td>
            <Td>◳</Td>
            <Td>◴</Td>
            <Td>◵</Td>
            <Td>◶</Td>
            <Td>◷</Td>
            <Td>◸</Td>
            <Td>◹</Td>
            <Td>◺</Td>
            <Td>◻</Td>
            <Td>◼</Td>
            <Td>◽</Td>
            <Td>◾</Td>
            <Td>◿</Td>
          </Tr>
          <Tr>
            <Td>0</Td>
            <Td>1</Td>
            <Td>2</Td>
            <Td>3</Td>
            <Td>4</Td>
            <Td>5</Td>
            <Td>6</Td>
            <Td>7</Td>
            <Td>8</Td>
            <Td>9</Td>
            <Td>a</Td>
            <Td>b</Td>
            <Td>c</Td>
            <Td>d</Td>
            <Td>e</Td>
            <Td>f</Td>
          </Tr>
          <Tr>
            <Td>☀</Td>
            <Td>☁</Td>
            <Td>☂</Td>
            <Td>☃</Td>
            <Td>☄</Td>
            <Td>★</Td>
            <Td>☆</Td>
            <Td>☇</Td>
            <Td>☈</Td>
            <Td>☉</Td>
            <Td>☊</Td>
            <Td>☋</Td>
            <Td>☌</Td>
            <Td>☍</Td>
            <Td>☎</Td>
            <Td>☏</Td>
          </Tr>
          <Tr>
            <Td>☐</Td>
            <Td>☑</Td>
            <Td>☒</Td>
            <Td>☓</Td>
            <Td>☔</Td>
            <Td>☕</Td>
            <Td>☖</Td>
            <Td>☗</Td>
            <Td>☘</Td>
            <Td>☙</Td>
            <Td>☚</Td>
            <Td>☛</Td>
            <Td>☜</Td>
            <Td>☝</Td>
            <Td>☞</Td>
            <Td>☟</Td>
          </Tr>
          <Tr>
            <Td>☠</Td>
            <Td>☡</Td>
            <Td>☢</Td>
            <Td>☣</Td>
            <Td>☤</Td>
            <Td>☥</Td>
            <Td>☦</Td>
            <Td>☧</Td>
            <Td>☨</Td>
            <Td>☩</Td>
            <Td>☪</Td>
            <Td>☫</Td>
            <Td>☬</Td>
            <Td>☭</Td>
            <Td>☮</Td>
            <Td>☯</Td>
          </Tr>
          <Tr>
            <Td>☰</Td>
            <Td>☱</Td>
            <Td>☲</Td>
            <Td>☳</Td>
            <Td>☴</Td>
            <Td>☵</Td>
            <Td>☶</Td>
            <Td>☷</Td>
            <Td>☸</Td>
            <Td>☹</Td>
            <Td>☺</Td>
            <Td>☻</Td>
            <Td>☼</Td>
            <Td>☽</Td>
            <Td>☾</Td>
            <Td>☿</Td>
          </Tr>
          <Tr>
            <Td>♀</Td>
            <Td>♁</Td>
            <Td>♂</Td>
            <Td>♃</Td>
            <Td>♄</Td>
            <Td>♅</Td>
            <Td>♆</Td>
            <Td>♇</Td>
            <Td>♈</Td>
            <Td>♉</Td>
            <Td>♊</Td>
            <Td>♋</Td>
            <Td>♌</Td>
            <Td>♍</Td>
            <Td>♎</Td>
            <Td>♏</Td>
          </Tr>
          <Tr>
            <Td>♐</Td>
            <Td>♑</Td>
            <Td>♒</Td>
            <Td>♓</Td>
            <Td>♔</Td>
            <Td>♕</Td>
            <Td>♖</Td>
            <Td>♗</Td>
            <Td>♘</Td>
            <Td>♙</Td>
            <Td>♚</Td>
            <Td>♛</Td>
            <Td>♜</Td>
            <Td>♝</Td>
            <Td>♞</Td>
            <Td>♟</Td>
          </Tr>
          <Tr>
            <Td>♠</Td>
            <Td>♡</Td>
            <Td>♢</Td>
            <Td>♣</Td>
            <Td>♤</Td>
            <Td>♥</Td>
            <Td>♦</Td>
            <Td>♧</Td>
            <Td>♨</Td>
            <Td>♩</Td>
            <Td>♪</Td>
            <Td>♫</Td>
            <Td>♬</Td>
            <Td>♭</Td>
            <Td>♮</Td>
            <Td>♯</Td>
          </Tr>
          <Tr>
            <Td>♰</Td>
            <Td>♱</Td>
            <Td>♲</Td>
            <Td>♳</Td>
            <Td>♴</Td>
            <Td>♵</Td>
            <Td>♶</Td>
            <Td>♷</Td>
            <Td>♸</Td>
            <Td>♹</Td>
            <Td>♺</Td>
            <Td>♻</Td>
            <Td>♼</Td>
            <Td>♽</Td>
            <Td>♾</Td>
            <Td>♿</Td>
          </Tr>
          <Tr>
            <Td>⚀</Td>
            <Td>⚁</Td>
            <Td>⚂</Td>
            <Td>⚃</Td>
            <Td>⚄</Td>
            <Td>⚅</Td>
            <Td>⚆</Td>
            <Td>⚇</Td>
            <Td>⚈</Td>
            <Td>⚉</Td>
            <Td>⚊</Td>
            <Td>⚋</Td>
            <Td>⚌</Td>
            <Td>⚍</Td>
            <Td>⚎</Td>
            <Td>⚏</Td>
          </Tr>
          <Tr>
            <Td>⚐</Td>
            <Td>⚑</Td>
            <Td>⚒</Td>
            <Td>⚓</Td>
            <Td>⚔</Td>
            <Td>⚕</Td>
            <Td>⚖</Td>
            <Td>⚗</Td>
            <Td>⚘</Td>
            <Td>⚙</Td>
            <Td>⚚</Td>
            <Td>⚛</Td>
            <Td>⚜</Td>
            <Td>⚝</Td>
            <Td>⚞</Td>
            <Td>⚟</Td>
          </Tr>
          <Tr>
            <Td>⚠</Td>
            <Td>⚡</Td>
            <Td>⚢</Td>
            <Td>⚣</Td>
            <Td>⚤</Td>
            <Td>⚥</Td>
            <Td>⚦</Td>
            <Td>⚧</Td>
            <Td>⚨</Td>
            <Td>⚩</Td>
            <Td>⚪</Td>
            <Td>⚫</Td>
            <Td>⚬</Td>
            <Td>⚭</Td>
            <Td>⚮</Td>
            <Td>⚯</Td>
          </Tr>
          <Tr>
            <Td>⚰</Td>
            <Td>⚱</Td>
            <Td>⚲</Td>
            <Td>⚳</Td>
            <Td>⚴</Td>
            <Td>⚵</Td>
            <Td>⚶</Td>
            <Td>⚷</Td>
            <Td>⚸</Td>
            <Td>⚹</Td>
            <Td>⚺</Td>
            <Td>⚻</Td>
            <Td>⚼</Td>
            <Td>⚽</Td>
            <Td>⚾</Td>
            <Td>⚿</Td>
          </Tr>
          <Tr>
            <Td>⛀</Td>
            <Td>⛁</Td>
            <Td>⛂</Td>
            <Td>⛃</Td>
            <Td>⛄</Td>
            <Td>⛅</Td>
            <Td>⛆</Td>
            <Td>⛇</Td>
            <Td>⛈</Td>
            <Td>⛉</Td>
            <Td>⛊</Td>
            <Td>⛋</Td>
            <Td>⛌</Td>
            <Td>⛍</Td>
            <Td>⛎</Td>
            <Td>⛏</Td>
          </Tr>
          <Tr>
            <Td>⛐</Td>
            <Td>⛑</Td>
            <Td>⛒</Td>
            <Td>⛓</Td>
            <Td>⛔</Td>
            <Td>⛕</Td>
            <Td>⛖</Td>
            <Td>⛗</Td>
            <Td>⛘</Td>
            <Td>⛙</Td>
            <Td>⛚</Td>
            <Td>⛛</Td>
            <Td>⛜</Td>
            <Td>⛝</Td>
            <Td>⛞</Td>
            <Td>⛟</Td>
          </Tr>
          <Tr>
            <Td>⛠</Td>
            <Td>⛡</Td>
            <Td>⛢</Td>
            <Td>⛣</Td>
            <Td>⛤</Td>
            <Td>⛥</Td>
            <Td>⛦</Td>
            <Td>⛧</Td>
            <Td>⛨</Td>
            <Td>⛩</Td>
            <Td>⛪</Td>
            <Td>⛫</Td>
            <Td>⛬</Td>
            <Td>⛭</Td>
            <Td>⛮</Td>
            <Td>⛯</Td>
          </Tr>
          <Tr>
            <Td>⛰</Td>
            <Td>⛱</Td>
            <Td>⛲</Td>
            <Td>⛳</Td>
            <Td>⛴</Td>
            <Td>⛵</Td>
            <Td>⛶</Td>
            <Td>⛷</Td>
            <Td>⛸</Td>
            <Td>⛹</Td>
            <Td>⛺</Td>
            <Td>⛻</Td>
            <Td>⛼</Td>
            <Td>⛽</Td>
            <Td>⛾</Td>
            <Td>⛿</Td>
          </Tr>
          <Tr>
            <Td>✀</Td>
            <Td>✁</Td>
            <Td>✂</Td>
            <Td>✃</Td>
            <Td>✄</Td>
            <Td>✅</Td>
            <Td>✆</Td>
            <Td>✇</Td>
            <Td>✈</Td>
            <Td>✉</Td>
            <Td>✊</Td>
            <Td>✋</Td>
            <Td>✌</Td>
            <Td>✍</Td>
            <Td>✎</Td>
            <Td>✏</Td>
          </Tr>
        </tbody>
      </table>
    </div>
  );
};
export default SpecialCharacters;
