const SpecialCharacters = () => {
  return (
    <section>
      <table>
        <tbody>
          <tr className="bg-slate-400 text-black">
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>a</td>
            <td>b</td>
            <td>c</td>
            <td>d</td>
            <td>e</td>
            <td>f</td>
          </tr>

          <tr>
            <td> </td>
            <td>!</td>
            <td>&#34;</td>
            <td>#</td>
            <td>$</td>
            <td>%</td>
            <td>&amp;</td>
            <td>&#39;</td>
            <td>(</td>
            <td>)</td>
            <td>*</td>
            <td>+</td>
            <td>,</td>
            <td>-</td>
            <td>.</td>
            <td>/</td>
          </tr>
          <tr>
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>:</td>
            <td>;</td>
            <td>&lt;</td>
            <td>=</td>
            <td>&gt;</td>
            <td>?</td>
          </tr>
          <tr>
            <td>@</td>
            <td>A</td>
            <td>B</td>
            <td>C</td>
            <td>D</td>
            <td>E</td>
            <td>F</td>
            <td>G</td>
            <td>H</td>
            <td>I</td>
            <td>J</td>
            <td>K</td>
            <td>L</td>
            <td>M</td>
            <td>N</td>
            <td>O</td>
          </tr>
          <tr>
            <td>P</td>
            <td>Q</td>
            <td>R</td>
            <td>S</td>
            <td>T</td>
            <td>U</td>
            <td>V</td>
            <td>W</td>
            <td>X</td>
            <td>Y</td>
            <td>Z</td>
            <td>[</td>
            <td>\</td>
            <td>]</td>
            <td>^</td>
            <td>_</td>
          </tr>
          <tr>
            <td>`</td>
            <td>a</td>
            <td>b</td>
            <td>c</td>
            <td>d</td>
            <td>e</td>
            <td>f</td>
            <td>g</td>
            <td>h</td>
            <td>i</td>
            <td>j</td>
            <td>k</td>
            <td>l</td>
            <td>m</td>
            <td>n</td>
            <td>o</td>
          </tr>
          <tr>
            <td>p</td>
            <td>q</td>
            <td>r</td>
            <td>s</td>
            <td>t</td>
            <td>u</td>
            <td>v</td>
            <td>w</td>
            <td>x</td>
            <td>y</td>
            <td>z</td>
            <td>&#123;</td>
            <td>|</td>
            <td>&#125;</td>
            <td>~</td>
            <td></td>
          </tr>
          <tr>
            <td>€</td>
            <td></td>
            <td>‚</td>
            <td>ƒ</td>
            <td>„</td>
            <td>…</td>
            <td>†</td>
            <td>‡</td>
            <td>ˆ</td>
            <td>‰</td>
            <td>Š</td>
            <td>‹</td>
            <td>Œ</td>
            <td></td>
            <td>Ž</td>
            <td></td>
          </tr>
          <tr>
            <td></td>
            <td>‘</td>
            <td>’</td>
            <td>“</td>
            <td>”</td>
            <td>•</td>
            <td>–</td>
            <td>—</td>
            <td>˜</td>
            <td>™</td>
            <td>š</td>
            <td>›</td>
            <td>œ</td>
            <td></td>
            <td>ž</td>
            <td>Ÿ</td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td>¡</td>
            <td>¢</td>
            <td>£</td>
            <td>¤</td>
            <td>¥</td>
            <td>¦</td>
            <td>§</td>
            <td>¨</td>
            <td>©</td>
            <td>ª</td>
            <td>«</td>
            <td>¬</td>
            <td>­</td>
            <td>®</td>
            <td>¯</td>
          </tr>
          <tr>
            <td>°</td>
            <td>±</td>
            <td>²</td>
            <td>³</td>
            <td>´</td>
            <td>µ</td>
            <td>¶</td>
            <td>·</td>
            <td>¸</td>
            <td>¹</td>
            <td>º</td>
            <td>»</td>
            <td>¼</td>
            <td>½</td>
            <td>¾</td>
            <td>¿</td>
          </tr>
          <tr>
            <td>À</td>
            <td>Á</td>
            <td>Â</td>
            <td>Ã</td>
            <td>Ä</td>
            <td>Å</td>
            <td>Æ</td>
            <td>Ç</td>
            <td>È</td>
            <td>É</td>
            <td>Ê</td>
            <td>Ë</td>
            <td>Ì</td>
            <td>Í</td>
            <td>Î</td>
            <td>Ï</td>
          </tr>
          <tr>
            <td>Ð</td>
            <td>Ñ</td>
            <td>Ò</td>
            <td>Ó</td>
            <td>Ô</td>
            <td>Õ</td>
            <td>Ö</td>
            <td>×</td>
            <td>Ø</td>
            <td>Ù</td>
            <td>Ú</td>
            <td>Û</td>
            <td>Ü</td>
            <td>Ý</td>
            <td>Þ</td>
            <td>ß</td>
          </tr>
          <tr>
            <td>à</td>
            <td>á</td>
            <td>â</td>
            <td>ã</td>
            <td>ä</td>
            <td>å</td>
            <td>æ</td>
            <td>ç</td>
            <td>è</td>
            <td>é</td>
            <td>ê</td>
            <td>ë</td>
            <td>ì</td>
            <td>í</td>
            <td>î</td>
            <td>ï</td>
          </tr>
          <tr>
            <td>ð</td>
            <td>ñ</td>
            <td>ò</td>
            <td>ó</td>
            <td>ô</td>
            <td>õ</td>
            <td>ö</td>
            <td>÷</td>
            <td>ø</td>
            <td>ù</td>
            <td>ú</td>
            <td>û</td>
            <td>ü</td>
            <td>ý</td>
            <td>þ</td>
            <td>ÿ</td>
          </tr>
          <tr>
            <td>Ā</td>
            <td>ā</td>
            <td>Ă</td>
            <td>ă</td>
            <td>Ą</td>
            <td>ą</td>
            <td>Ć</td>
            <td>ć</td>
            <td>Ĉ</td>
            <td>ĉ</td>
            <td>Ċ</td>
            <td>ċ</td>
            <td>Č</td>
            <td>č</td>
            <td>Ď</td>
            <td>ď</td>
          </tr>
          <tr>
            <td>Đ</td>
            <td>đ</td>
            <td>Ē</td>
            <td>ē</td>
            <td>Ĕ</td>
            <td>ĕ</td>
            <td>Ė</td>
            <td>ė</td>
            <td>Ę</td>
            <td>ę</td>
            <td>Ě</td>
            <td>ě</td>
            <td>Ĝ</td>
            <td>ĝ</td>
            <td>Ğ</td>
            <td>ğ</td>
          </tr>
          <tr>
            <td>Ġ</td>
            <td>ġ</td>
            <td>Ģ</td>
            <td>ģ</td>
            <td>Ĥ</td>
            <td>ĥ</td>
            <td>Ħ</td>
            <td>ħ</td>
            <td>Ĩ</td>
            <td>ĩ</td>
            <td>Ī</td>
            <td>ī</td>
            <td>Ĭ</td>
            <td>ĭ</td>
            <td>Į</td>
            <td>į</td>
          </tr>
          <tr>
            <td>İ</td>
            <td>ı</td>
            <td>Ĳ</td>
            <td>ĳ</td>
            <td>Ĵ</td>
            <td>ĵ</td>
            <td>Ķ</td>
            <td>ķ</td>
            <td>ĸ</td>
            <td>Ĺ</td>
            <td>ĺ</td>
            <td>Ļ</td>
            <td>ļ</td>
            <td>Ľ</td>
            <td>ľ</td>
            <td>Ŀ</td>
          </tr>
          <tr>
            <td>ŀ</td>
            <td>Ł</td>
            <td>ł</td>
            <td>Ń</td>
            <td>ń</td>
            <td>Ņ</td>
            <td>ņ</td>
            <td>Ň</td>
            <td>ň</td>
            <td>ŉ</td>
            <td>Ŋ</td>
            <td>ŋ</td>
            <td>Ō</td>
            <td>ō</td>
            <td>Ŏ</td>
            <td>ŏ</td>
          </tr>
          <tr>
            <td>Ő</td>
            <td>ő</td>
            <td>Œ</td>
            <td>œ</td>
            <td>Ŕ</td>
            <td>ŕ</td>
            <td>Ŗ</td>
            <td>ŗ</td>
            <td>Ř</td>
            <td>ř</td>
            <td>Ś</td>
            <td>ś</td>
            <td>Ŝ</td>
            <td>ŝ</td>
            <td>Ş</td>
            <td>ş</td>
          </tr>
          <tr>
            <td>Š</td>
            <td>š</td>
            <td>Ţ</td>
            <td>ţ</td>
            <td>Ť</td>
            <td>ť</td>
            <td>Ŧ</td>
            <td>ŧ</td>
            <td>Ũ</td>
            <td>ũ</td>
            <td>Ū</td>
            <td>ū</td>
            <td>Ŭ</td>
            <td>ŭ</td>
            <td>Ů</td>
            <td>ů</td>
          </tr>
          <tr>
            <td>Ű</td>
            <td>ű</td>
            <td>Ų</td>
            <td>ų</td>
            <td>Ŵ</td>
            <td>ŵ</td>
            <td>Ŷ</td>
            <td>ŷ</td>
            <td>Ÿ</td>
            <td>Ź</td>
            <td>ź</td>
            <td>Ż</td>
            <td>ż</td>
            <td>Ž</td>
            <td>ž</td>
            <td>ſ</td>
          </tr>
          <tr>
            <td>ƀ</td>
            <td>Ɓ</td>
            <td>Ƃ</td>
            <td>ƃ</td>
            <td>Ƅ</td>
            <td>ƅ</td>
            <td>Ɔ</td>
            <td>Ƈ</td>
            <td>ƈ</td>
            <td>Ɖ</td>
            <td>Ɗ</td>
            <td>Ƌ</td>
            <td>ƌ</td>
            <td>ƍ</td>
            <td>Ǝ</td>
            <td>Ə</td>
          </tr>
          <tr>
            <td>Ɛ</td>
            <td>Ƒ</td>
            <td>ƒ</td>
            <td>Ɠ</td>
            <td>Ɣ</td>
            <td>ƕ</td>
            <td>Ɩ</td>
            <td>Ɨ</td>
            <td>Ƙ</td>
            <td>ƙ</td>
            <td>ƚ</td>
            <td>ƛ</td>
            <td>Ɯ</td>
            <td>Ɲ</td>
            <td>ƞ</td>
            <td>Ɵ</td>
          </tr>
          <tr>
            <td>Ơ</td>
            <td>ơ</td>
            <td>Ƣ</td>
            <td>ƣ</td>
            <td>Ƥ</td>
            <td>ƥ</td>
            <td>Ʀ</td>
            <td>Ƨ</td>
            <td>ƨ</td>
            <td>Ʃ</td>
            <td>ƪ</td>
            <td>ƫ</td>
            <td>Ƭ</td>
            <td>ƭ</td>
            <td>Ʈ</td>
            <td>Ư</td>
          </tr>
          <tr>
            <td>ư</td>
            <td>Ʊ</td>
            <td>Ʋ</td>
            <td>Ƴ</td>
            <td>ƴ</td>
            <td>Ƶ</td>
            <td>ƶ</td>
            <td>Ʒ</td>
            <td>Ƹ</td>
            <td>ƹ</td>
            <td>ƺ</td>
            <td>ƻ</td>
            <td>Ƽ</td>
            <td>ƽ</td>
            <td>ƾ</td>
            <td>ƿ</td>
          </tr>
          <tr>
            <td>ǀ</td>
            <td>ǁ</td>
            <td>ǂ</td>
            <td>ǃ</td>
            <td>Ǆ</td>
            <td>ǅ</td>
            <td>ǆ</td>
            <td>Ǉ</td>
            <td>ǈ</td>
            <td>ǉ</td>
            <td>Ǌ</td>
            <td>ǋ</td>
            <td>ǌ</td>
            <td>Ǎ</td>
            <td>ǎ</td>
            <td>Ǐ</td>
          </tr>
          <tr>
            <td>ǐ</td>
            <td>Ǒ</td>
            <td>ǒ</td>
            <td>Ǔ</td>
            <td>ǔ</td>
            <td>Ǖ</td>
            <td>ǖ</td>
            <td>Ǘ</td>
            <td>ǘ</td>
            <td>Ǚ</td>
            <td>ǚ</td>
            <td>Ǜ</td>
            <td>ǜ</td>
            <td>ǝ</td>
            <td>Ǟ</td>
            <td>ǟ</td>
          </tr>
          <tr>
            <td>Ǡ</td>
            <td>ǡ</td>
            <td>Ǣ</td>
            <td>ǣ</td>
            <td>Ǥ</td>
            <td>ǥ</td>
            <td>Ǧ</td>
            <td>ǧ</td>
            <td>Ǩ</td>
            <td>ǩ</td>
            <td>Ǫ</td>
            <td>ǫ</td>
            <td>Ǭ</td>
            <td>ǭ</td>
            <td>Ǯ</td>
            <td>ǯ</td>
          </tr>
          <tr>
            <td>ǰ</td>
            <td>Ǳ</td>
            <td>ǲ</td>
            <td>ǳ</td>
            <td>Ǵ</td>
            <td>ǵ</td>
            <td>Ƕ</td>
            <td>Ƿ</td>
            <td>Ǹ</td>
            <td>ǹ</td>
            <td>Ǻ</td>
            <td>ǻ</td>
            <td>Ǽ</td>
            <td>ǽ</td>
            <td>Ǿ</td>
            <td>ǿ</td>
          </tr>
          <tr className="bg-slate-400 text-black">
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>a</td>
            <td>b</td>
            <td>c</td>
            <td>d</td>
            <td>e</td>
            <td>f</td>
          </tr>
          <tr>
            <td>Ȁ</td>
            <td>ȁ</td>
            <td>Ȃ</td>
            <td>ȃ</td>
            <td>Ȅ</td>
            <td>ȅ</td>
            <td>Ȇ</td>
            <td>ȇ</td>
            <td>Ȉ</td>
            <td>ȉ</td>
            <td>Ȋ</td>
            <td>ȋ</td>
            <td>Ȍ</td>
            <td>ȍ</td>
            <td>Ȏ</td>
            <td>ȏ</td>
          </tr>
          <tr>
            <td>Ȑ</td>
            <td>ȑ</td>
            <td>Ȓ</td>
            <td>ȓ</td>
            <td>Ȕ</td>
            <td>ȕ</td>
            <td>Ȗ</td>
            <td>ȗ</td>
            <td>Ș</td>
            <td>ș</td>
            <td>Ț</td>
            <td>ț</td>
            <td>Ȝ</td>
            <td>ȝ</td>
            <td>Ȟ</td>
            <td>ȟ</td>
          </tr>
          <tr>
            <td>Ƞ</td>
            <td>ȡ</td>
            <td>Ȣ</td>
            <td>ȣ</td>
            <td>Ȥ</td>
            <td>ȥ</td>
            <td>Ȧ</td>
            <td>ȧ</td>
            <td>Ȩ</td>
            <td>ȩ</td>
            <td>Ȫ</td>
            <td>ȫ</td>
            <td>Ȭ</td>
            <td>ȭ</td>
            <td>Ȯ</td>
            <td>ȯ</td>
          </tr>
          <tr>
            <td>Ȱ</td>
            <td>ȱ</td>
            <td>Ȳ</td>
            <td>ȳ</td>
            <td>ȴ</td>
            <td>ȵ</td>
            <td>ȶ</td>
            <td>ȷ</td>
            <td>ȸ</td>
            <td>ȹ</td>
            <td>Ⱥ</td>
            <td>Ȼ</td>
            <td>ȼ</td>
            <td>Ƚ</td>
            <td>Ⱦ</td>
            <td>ȿ</td>
          </tr>
          <tr>
            <td>ɀ</td>
            <td>Ɂ</td>
            <td>ɂ</td>
            <td>Ƀ</td>
            <td>Ʉ</td>
            <td>Ʌ</td>
            <td>Ɇ</td>
            <td>ɇ</td>
            <td>Ɉ</td>
            <td>ɉ</td>
            <td>Ɋ</td>
            <td>ɋ</td>
            <td>Ɍ</td>
            <td>ɍ</td>
            <td>Ɏ</td>
            <td>ɏ</td>
          </tr>
          <tr>
            <td>ɐ</td>
            <td>ɑ</td>
            <td>ɒ</td>
            <td>ɓ</td>
            <td>ɔ</td>
            <td>ɕ</td>
            <td>ɖ</td>
            <td>ɗ</td>
            <td>ɘ</td>
            <td>ə</td>
            <td>ɚ</td>
            <td>ɛ</td>
            <td>ɜ</td>
            <td>ɝ</td>
            <td>ɞ</td>
            <td>ɟ</td>
          </tr>
          <tr>
            <td>ɠ</td>
            <td>ɡ</td>
            <td>ɢ</td>
            <td>ɣ</td>
            <td>ɤ</td>
            <td>ɥ</td>
            <td>ɦ</td>
            <td>ɧ</td>
            <td>ɨ</td>
            <td>ɩ</td>
            <td>ɪ</td>
            <td>ɫ</td>
            <td>ɬ</td>
            <td>ɭ</td>
            <td>ɮ</td>
            <td>ɯ</td>
          </tr>
          <tr>
            <td>ɰ</td>
            <td>ɱ</td>
            <td>ɲ</td>
            <td>ɳ</td>
            <td>ɴ</td>
            <td>ɵ</td>
            <td>ɶ</td>
            <td>ɷ</td>
            <td>ɸ</td>
            <td>ɹ</td>
            <td>ɺ</td>
            <td>ɻ</td>
            <td>ɼ</td>
            <td>ɽ</td>
            <td>ɾ</td>
            <td>ɿ</td>
          </tr>
          <tr>
            <td>ʀ</td>
            <td>ʁ</td>
            <td>ʂ</td>
            <td>ʃ</td>
            <td>ʄ</td>
            <td>ʅ</td>
            <td>ʆ</td>
            <td>ʇ</td>
            <td>ʈ</td>
            <td>ʉ</td>
            <td>ʊ</td>
            <td>ʋ</td>
            <td>ʌ</td>
            <td>ʍ</td>
            <td>ʎ</td>
            <td>ʏ</td>
          </tr>
          <tr>
            <td>ʐ</td>
            <td>ʑ</td>
            <td>ʒ</td>
            <td>ʓ</td>
            <td>ʔ</td>
            <td>ʕ</td>
            <td>ʖ</td>
            <td>ʗ</td>
            <td>ʘ</td>
            <td>ʙ</td>
            <td>ʚ</td>
            <td>ʛ</td>
            <td>ʜ</td>
            <td>ʝ</td>
            <td>ʞ</td>
            <td>ʟ</td>
          </tr>
          <tr>
            <td>ʠ</td>
            <td>ʡ</td>
            <td>ʢ</td>
            <td>ʣ</td>
            <td>ʤ</td>
            <td>ʥ</td>
            <td>ʦ</td>
            <td>ʧ</td>
            <td>ʨ</td>
            <td>ʩ</td>
            <td>ʪ</td>
            <td>ʫ</td>
            <td>ʬ</td>
            <td>ʭ</td>
            <td>ʮ</td>
            <td>ʯ</td>
          </tr>
          <tr>
            <td>ʰ</td>
            <td>ʱ</td>
            <td>ʲ</td>
            <td>ʳ</td>
            <td>ʴ</td>
            <td>ʵ</td>
            <td>ʶ</td>
            <td>ʷ</td>
            <td>ʸ</td>
            <td>ʹ</td>
            <td>ʺ</td>
            <td>ʻ</td>
            <td>ʼ</td>
            <td>ʽ</td>
            <td>ʾ</td>
            <td>ʿ</td>
          </tr>
          <tr>
            <td>ˀ</td>
            <td>ˁ</td>
            <td>˂</td>
            <td>˃</td>
            <td>˄</td>
            <td>˅</td>
            <td>ˆ</td>
            <td>ˇ</td>
            <td>ˈ</td>
            <td>ˉ</td>
            <td>ˊ</td>
            <td>ˋ</td>
            <td>ˌ</td>
            <td>ˍ</td>
            <td>ˎ</td>
            <td>ˏ</td>
          </tr>
          <tr>
            <td>ː</td>
            <td>ˑ</td>
            <td>˒</td>
            <td>˓</td>
            <td>˔</td>
            <td>˕</td>
            <td>˖</td>
            <td>˗</td>
            <td>˘</td>
            <td>˙</td>
            <td>˚</td>
            <td>˛</td>
            <td>˜</td>
            <td>˝</td>
            <td>˞</td>
            <td>˟</td>
          </tr>
          <tr>
            <td>ˠ</td>
            <td>ˡ</td>
            <td>ˢ</td>
            <td>ˣ</td>
            <td>ˤ</td>
            <td>˥</td>
            <td>˦</td>
            <td>˧</td>
            <td>˨</td>
            <td>˩</td>
            <td>˪</td>
            <td>˫</td>
            <td>ˬ</td>
            <td>˭</td>
            <td>ˮ</td>
            <td>˯</td>
          </tr>
          <tr>
            <td>˰</td>
            <td>˱</td>
            <td>˲</td>
            <td>˳</td>
            <td>˴</td>
            <td>˵</td>
            <td>˶</td>
            <td>˷</td>
            <td>˸</td>
            <td>˹</td>
            <td>˺</td>
            <td>˻</td>
            <td>˼</td>
            <td>˽</td>
            <td>˾</td>
            <td>˿</td>
          </tr>
          <tr>
            <td>̀</td>
            <td>́</td>
            <td>̂</td>
            <td>̃</td>
            <td>̄</td>
            <td>̅</td>
            <td>̆</td>
            <td>̇</td>
            <td>̈</td>
            <td>̉</td>
            <td>̊</td>
            <td>̋</td>
            <td>̌</td>
            <td>̍</td>
            <td>̎</td>
            <td>̏</td>
          </tr>
          <tr>
            <td>̐</td>
            <td>̑</td>
            <td>̒</td>
            <td>̓</td>
            <td>̔</td>
            <td>̕</td>
            <td>̖</td>
            <td>̗</td>
            <td>̘</td>
            <td>̙</td>
            <td>̚</td>
            <td>̛</td>
            <td>̜</td>
            <td>̝</td>
            <td>̞</td>
            <td>̟</td>
          </tr>
          <tr>
            <td>̠</td>
            <td>̡</td>
            <td>̢</td>
            <td>̣</td>
            <td>̤</td>
            <td>̥</td>
            <td>̦</td>
            <td>̧</td>
            <td>̨</td>
            <td>̩</td>
            <td>̪</td>
            <td>̫</td>
            <td>̬</td>
            <td>̭</td>
            <td>̮</td>
            <td>̯</td>
          </tr>
          <tr>
            <td>̰</td>
            <td>̱</td>
            <td>̲</td>
            <td>̳</td>
            <td>̴</td>
            <td>̵</td>
            <td>̶</td>
            <td>̷</td>
            <td≯</td>
            <td>̹</td>
            <td>̺</td>
            <td>̻</td>
            <td>̼</td>
            <td>̽</td>
            <td>̾</td>
            <td>̿</td>
          </tr>
          <tr>
            <td>̀</td>
            <td>́</td>
            <td>͂</td>
            <td>̓</td>
            <td>̈́</td>
            <td>ͅ</td>
            <td>͆</td>
            <td>͇</td>
            <td>͈</td>
            <td>͉</td>
            <td>͊</td>
            <td>͋</td>
            <td>͌</td>
            <td>͍</td>
            <td>͎</td>
            <td>͏</td>
          </tr>
          <tr>
            <td>͐</td>
            <td>͑</td>
            <td>͒</td>
            <td>͓</td>
            <td>͔</td>
            <td>͕</td>
            <td>͖</td>
            <td>͗</td>
            <td>͘</td>
            <td>͙</td>
            <td>͚</td>
            <td>͛</td>
            <td>͜</td>
            <td>͝</td>
            <td>͞</td>
            <td>͟</td>
          </tr>
          <tr>
            <td>͠</td>
            <td>͡</td>
            <td>͢</td>
            <td>ͣ</td>
            <td>ͤ</td>
            <td>ͥ</td>
            <td>ͦ</td>
            <td>ͧ</td>
            <td>ͨ</td>
            <td>ͩ</td>
            <td>ͪ</td>
            <td>ͫ</td>
            <td>ͬ</td>
            <td>ͭ</td>
            <td>ͮ</td>
            <td>ͯ</td>
          </tr>
          <tr>
            <td>Ͱ</td>
            <td>ͱ</td>
            <td>Ͳ</td>
            <td>ͳ</td>
            <td>ʹ</td>
            <td>͵</td>
            <td>Ͷ</td>
            <td>ͷ</td>
            <td>͸</td>
            <td>͹</td>
            <td>ͺ</td>
            <td>ͻ</td>
            <td>ͼ</td>
            <td>ͽ</td>
            <td>;</td>
            <td>Ϳ</td>
          </tr>
          <tr>
            <td>΀</td>
            <td>΁</td>
            <td>΂</td>
            <td>΃</td>
            <td>΄</td>
            <td>΅</td>
            <td>Ά</td>
            <td>·</td>
            <td>Έ</td>
            <td>Ή</td>
            <td>Ί</td>
            <td>΋</td>
            <td>Ό</td>
            <td>΍</td>
            <td>Ύ</td>
            <td>Ώ</td>
          </tr>
          <tr>
            <td>ΐ</td>
            <td>Α</td>
            <td>Β</td>
            <td>Γ</td>
            <td>Δ</td>
            <td>Ε</td>
            <td>Ζ</td>
            <td>Η</td>
            <td>Θ</td>
            <td>Ι</td>
            <td>Κ</td>
            <td>Λ</td>
            <td>Μ</td>
            <td>Ν</td>
            <td>Ξ</td>
            <td>Ο</td>
          </tr>
          <tr>
            <td>Π</td>
            <td>Ρ</td>
            <td>΢</td>
            <td>Σ</td>
            <td>Τ</td>
            <td>Υ</td>
            <td>Φ</td>
            <td>Χ</td>
            <td>Ψ</td>
            <td>Ω</td>
            <td>Ϊ</td>
            <td>Ϋ</td>
            <td>ά</td>
            <td>έ</td>
            <td>ή</td>
            <td>ί</td>
          </tr>
          <tr>
            <td>ΰ</td>
            <td>α</td>
            <td>β</td>
            <td>γ</td>
            <td>δ</td>
            <td>ε</td>
            <td>ζ</td>
            <td>η</td>
            <td>θ</td>
            <td>ι</td>
            <td>κ</td>
            <td>λ</td>
            <td>μ</td>
            <td>ν</td>
            <td>ξ</td>
            <td>ο</td>
          </tr>
          <tr>
            <td>π</td>
            <td>ρ</td>
            <td>ς</td>
            <td>σ</td>
            <td>τ</td>
            <td>υ</td>
            <td>φ</td>
            <td>χ</td>
            <td>ψ</td>
            <td>ω</td>
            <td>ϊ</td>
            <td>ϋ</td>
            <td>ό</td>
            <td>ύ</td>
            <td>ώ</td>
            <td>Ϗ</td>
          </tr>
          <tr>
            <td>ϐ</td>
            <td>ϑ</td>
            <td>ϒ</td>
            <td>ϓ</td>
            <td>ϔ</td>
            <td>ϕ</td>
            <td>ϖ</td>
            <td>ϗ</td>
            <td>Ϙ</td>
            <td>ϙ</td>
            <td>Ϛ</td>
            <td>ϛ</td>
            <td>Ϝ</td>
            <td>ϝ</td>
            <td>Ϟ</td>
            <td>ϟ</td>
          </tr>
          <tr>
            <td>Ϡ</td>
            <td>ϡ</td>
            <td>Ϣ</td>
            <td>ϣ</td>
            <td>Ϥ</td>
            <td>ϥ</td>
            <td>Ϧ</td>
            <td>ϧ</td>
            <td>Ϩ</td>
            <td>ϩ</td>
            <td>Ϫ</td>
            <td>ϫ</td>
            <td>Ϭ</td>
            <td>ϭ</td>
            <td>Ϯ</td>
            <td>ϯ</td>
          </tr>
          <tr className="bg-slate-400 text-black">
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>a</td>
            <td>b</td>
            <td>c</td>
            <td>d</td>
            <td>e</td>
            <td>f</td>
          </tr>
          <tr>
            <td> </td>
            <td> </td>
            <td> </td>
            <td> </td>
            <td> </td>
            <td> </td>
            <td> </td>
            <td> </td>
            <td> </td>
            <td> </td>
            <td> </td>
            <td>​</td>
            <td>‌</td>
            <td>‍</td>
            <td>‎</td>
            <td>‏</td>
          </tr>
          <tr>
            <td>‐</td>
            <td>‑</td>
            <td>‒</td>
            <td>–</td>
            <td>—</td>
            <td>―</td>
            <td>‖</td>
            <td>‗</td>
            <td>‘</td>
            <td>’</td>
            <td>‚</td>
            <td>‛</td>
            <td>“</td>
            <td>”</td>
            <td>„</td>
            <td>‟</td>
          </tr>
          <tr>
            <td>†</td>
            <td>‡</td>
            <td>•</td>
            <td>‣</td>
            <td>․</td>
            <td>‥</td>
            <td>…</td>
            <td>‧</td>
            <td></td>
            <td></td>
            <td>‪</td>
            <td>‫</td>
            <td>‬</td>
            <td>‭</td>
            <td>‮</td>
            <td> </td>
          </tr>
          <tr>
            <td>‰</td>
            <td>‱</td>
            <td>′</td>
            <td>″</td>
            <td>‴</td>
            <td>‵</td>
            <td>‶</td>
            <td>‷</td>
            <td>‸</td>
            <td>‹</td>
            <td>›</td>
            <td>※</td>
            <td>‼</td>
            <td>‽</td>
            <td>‾</td>
            <td>‿</td>
          </tr>
          <tr>
            <td>⁀</td>
            <td>⁁</td>
            <td>⁂</td>
            <td>⁃</td>
            <td>⁄</td>
            <td>⁅</td>
            <td>⁆</td>
            <td>⁇</td>
            <td>⁈</td>
            <td>⁉</td>
            <td>⁊</td>
            <td>⁋</td>
            <td>⁌</td>
            <td>⁍</td>
            <td>⁎</td>
            <td>⁏</td>
          </tr>
          <tr>
            <td>⁐</td>
            <td>⁑</td>
            <td>⁒</td>
            <td>⁓</td>
            <td>⁔</td>
            <td>⁕</td>
            <td>⁖</td>
            <td>⁗</td>
            <td>⁘</td>
            <td>⁙</td>
            <td>⁚</td>
            <td>⁛</td>
            <td>⁜</td>
            <td>⁝</td>
            <td>⁞</td>
            <td> </td>
          </tr>
          <tr>
            <td>⁠</td>
            <td>⁡</td>
            <td>⁢</td>
            <td>⁣</td>
            <td>⁤</td>
            <td>⁥</td>
            <td>⁦</td>
            <td>⁧</td>
            <td>⁨</td>
            <td>⁩</td>
            <td>⁪</td>
            <td>⁫</td>
            <td>⁬</td>
            <td>⁭</td>
            <td>⁮</td>
            <td>⁯</td>
          </tr>
          <tr>
            <td>⁰</td>
            <td>ⁱ</td>
            <td>⁲</td>
            <td>⁳</td>
            <td>⁴</td>
            <td>⁵</td>
            <td>⁶</td>
            <td>⁷</td>
            <td>⁸</td>
            <td>⁹</td>
            <td>⁺</td>
            <td>⁻</td>
            <td>⁼</td>
            <td>⁽</td>
            <td>⁾</td>
            <td>ⁿ</td>
          </tr>
          <tr>
            <td>₀</td>
            <td>₁</td>
            <td>₂</td>
            <td>₃</td>
            <td>₄</td>
            <td>₅</td>
            <td>₆</td>
            <td>₇</td>
            <td>₈</td>
            <td>₉</td>
            <td>₊</td>
            <td>₋</td>
            <td>₌</td>
            <td>₍</td>
            <td>₎</td>
            <td>₏</td>
          </tr>
          <tr>
            <td>ₐ</td>
            <td>ₑ</td>
            <td>ₒ</td>
            <td>ₓ</td>
            <td>ₔ</td>
            <td>ₕ</td>
            <td>ₖ</td>
            <td>ₗ</td>
            <td>ₘ</td>
            <td>ₙ</td>
            <td>ₚ</td>
            <td>ₛ</td>
            <td>ₜ</td>
            <td>₝</td>
            <td>₞</td>
            <td>₟</td>
          </tr>
          <tr>
            <td>₠</td>
            <td>₡</td>
            <td>₢</td>
            <td>₣</td>
            <td>₤</td>
            <td>₥</td>
            <td>₦</td>
            <td>₧</td>
            <td>₨</td>
            <td>₩</td>
            <td>₪</td>
            <td>₫</td>
            <td>€</td>
            <td>₭</td>
            <td>₮</td>
            <td>₯</td>
          </tr>
          <tr>
            <td>₰</td>
            <td>₱</td>
            <td>₲</td>
            <td>₳</td>
            <td>₴</td>
            <td>₵</td>
            <td>₶</td>
            <td>₷</td>
            <td>₸</td>
            <td>₹</td>
            <td>₺</td>
            <td>₻</td>
            <td>₼</td>
            <td>₽</td>
            <td>₾</td>
            <td>₿</td>
          </tr>
          <tr>
            <td>⃀</td>
            <td>⃁</td>
            <td>⃂</td>
            <td>⃃</td>
            <td>⃄</td>
            <td>⃅</td>
            <td>⃆</td>
            <td>⃇</td>
            <td>⃈</td>
            <td>⃉</td>
            <td>⃊</td>
            <td>⃋</td>
            <td>⃌</td>
            <td>⃍</td>
            <td>⃎</td>
            <td>⃏</td>
          </tr>
          <tr>
            <td>⃐</td>
            <td>⃑</td>
            <td>⃒</td>
            <td>⃓</td>
            <td>⃔</td>
            <td>⃕</td>
            <td>⃖</td>
            <td>⃗</td>
            <td>⃘</td>
            <td>⃙</td>
            <td>⃚</td>
            <td>⃛</td>
            <td>⃜</td>
            <td>⃝</td>
            <td>⃞</td>
            <td>⃟</td>
          </tr>
          <tr>
            <td>⃠</td>
            <td>⃡</td>
            <td>⃢</td>
            <td>⃣</td>
            <td>⃤</td>
            <td>⃥</td>
            <td>⃦</td>
            <td>⃧</td>
            <td>⃨</td>
            <td>⃩</td>
            <td>⃪</td>
            <td>⃫</td>
            <td>⃬</td>
            <td>⃭</td>
            <td>⃮</td>
            <td>⃯</td>
          </tr>
          <tr>
            <td>⃰</td>
            <td>⃱</td>
            <td>⃲</td>
            <td>⃳</td>
            <td>⃴</td>
            <td>⃵</td>
            <td>⃶</td>
            <td>⃷</td>
            <td>⃸</td>
            <td>⃹</td>
            <td>⃺</td>
            <td>⃻</td>
            <td>⃼</td>
            <td>⃽</td>
            <td>⃾</td>
            <td>⃿</td>
          </tr>
          <tr>
            <td>℀</td>
            <td>℁</td>
            <td>ℂ</td>
            <td>℃</td>
            <td>℄</td>
            <td>℅</td>
            <td>℆</td>
            <td>ℇ</td>
            <td>℈</td>
            <td>℉</td>
            <td>ℊ</td>
            <td>ℋ</td>
            <td>ℌ</td>
            <td>ℍ</td>
            <td>ℎ</td>
            <td>ℏ</td>
          </tr>
          <tr>
            <td>ℐ</td>
            <td>ℑ</td>
            <td>ℒ</td>
            <td>ℓ</td>
            <td>℔</td>
            <td>ℕ</td>
            <td>№</td>
            <td>℗</td>
            <td>℘</td>
            <td>ℙ</td>
            <td>ℚ</td>
            <td>ℛ</td>
            <td>ℜ</td>
            <td>ℝ</td>
            <td>℞</td>
            <td>℟</td>
          </tr>
          <tr>
            <td>℠</td>
            <td>℡</td>
            <td>™</td>
            <td>℣</td>
            <td>ℤ</td>
            <td>℥</td>
            <td>Ω</td>
            <td>℧</td>
            <td>ℨ</td>
            <td>℩</td>
            <td>K</td>
            <td>Å</td>
            <td>ℬ</td>
            <td>ℭ</td>
            <td>℮</td>
            <td>ℯ</td>
          </tr>
          <tr>
            <td>ℰ</td>
            <td>ℱ</td>
            <td>Ⅎ</td>
            <td>ℳ</td>
            <td>ℴ</td>
            <td>ℵ</td>
            <td>ℶ</td>
            <td>ℷ</td>
            <td>ℸ</td>
            <td>ℹ</td>
            <td>℺</td>
            <td>℻</td>
            <td>ℼ</td>
            <td>ℽ</td>
            <td>ℾ</td>
            <td>ℿ</td>
          </tr>
          <tr>
            <td>⅀</td>
            <td>⅁</td>
            <td>⅂</td>
            <td>⅃</td>
            <td>⅄</td>
            <td>ⅅ</td>
            <td>ⅆ</td>
            <td>ⅇ</td>
            <td>ⅈ</td>
            <td>ⅉ</td>
            <td>⅊</td>
            <td>⅋</td>
            <td>⅌</td>
            <td>⅍</td>
            <td>ⅎ</td>
            <td>⅏</td>
          </tr>
          <tr>
            <td>⅐</td>
            <td>⅑</td>
            <td>⅒</td>
            <td>⅓</td>
            <td>⅔</td>
            <td>⅕</td>
            <td>⅖</td>
            <td>⅗</td>
            <td>⅘</td>
            <td>⅙</td>
            <td>⅚</td>
            <td>⅛</td>
            <td>⅜</td>
            <td>⅝</td>
            <td>⅞</td>
            <td>⅟</td>
          </tr>
          <tr>
            <td>Ⅰ</td>
            <td>Ⅱ</td>
            <td>Ⅲ</td>
            <td>Ⅳ</td>
            <td>Ⅴ</td>
            <td>Ⅵ</td>
            <td>Ⅶ</td>
            <td>Ⅷ</td>
            <td>Ⅸ</td>
            <td>Ⅹ</td>
            <td>Ⅺ</td>
            <td>Ⅻ</td>
            <td>Ⅼ</td>
            <td>Ⅽ</td>
            <td>Ⅾ</td>
            <td>Ⅿ</td>
          </tr>
          <tr>
            <td>ⅰ</td>
            <td>ⅱ</td>
            <td>ⅲ</td>
            <td>ⅳ</td>
            <td>ⅴ</td>
            <td>ⅵ</td>
            <td>ⅶ</td>
            <td>ⅷ</td>
            <td>ⅸ</td>
            <td>ⅹ</td>
            <td>ⅺ</td>
            <td>ⅻ</td>
            <td>ⅼ</td>
            <td>ⅽ</td>
            <td>ⅾ</td>
            <td>ⅿ</td>
          </tr>
          <tr>
            <td>ↀ</td>
            <td>ↁ</td>
            <td>ↂ</td>
            <td>Ↄ</td>
            <td>ↄ</td>
            <td>ↅ</td>
            <td>ↆ</td>
            <td>ↇ</td>
            <td>ↈ</td>
            <td>↉</td>
            <td>↊</td>
            <td>↋</td>
            <td>↌</td>
            <td>↍</td>
            <td>↎</td>
            <td>↏</td>
          </tr>
          <tr>
            <td>←</td>
            <td>↑</td>
            <td>→</td>
            <td>↓</td>
            <td>↔</td>
            <td>↕</td>
            <td>↖</td>
            <td>↗</td>
            <td>↘</td>
            <td>↙</td>
            <td>↚</td>
            <td>↛</td>
            <td>↜</td>
            <td>↝</td>
            <td>↞</td>
            <td>↟</td>
          </tr>
          <tr>
            <td>↠</td>
            <td>↡</td>
            <td>↢</td>
            <td>↣</td>
            <td>↤</td>
            <td>↥</td>
            <td>↦</td>
            <td>↧</td>
            <td>↨</td>
            <td>↩</td>
            <td>↪</td>
            <td>↫</td>
            <td>↬</td>
            <td>↭</td>
            <td>↮</td>
            <td>↯</td>
          </tr>
          <tr>
            <td>↰</td>
            <td>↱</td>
            <td>↲</td>
            <td>↳</td>
            <td>↴</td>
            <td>↵</td>
            <td>↶</td>
            <td>↷</td>
            <td>↸</td>
            <td>↹</td>
            <td>↺</td>
            <td>↻</td>
            <td>↼</td>
            <td>↽</td>
            <td>↾</td>
            <td>↿</td>
          </tr>
          <tr>
            <td>⇀</td>
            <td>⇁</td>
            <td>⇂</td>
            <td>⇃</td>
            <td>⇄</td>
            <td>⇅</td>
            <td>⇆</td>
            <td>⇇</td>
            <td>⇈</td>
            <td>⇉</td>
            <td>⇊</td>
            <td>⇋</td>
            <td>⇌</td>
            <td>⇍</td>
            <td>⇎</td>
            <td>⇏</td>
          </tr>
          <tr>
            <td>⇐</td>
            <td>⇑</td>
            <td>⇒</td>
            <td>⇓</td>
            <td>⇔</td>
            <td>⇕</td>
            <td>⇖</td>
            <td>⇗</td>
            <td>⇘</td>
            <td>⇙</td>
            <td>⇚</td>
            <td>⇛</td>
            <td>⇜</td>
            <td>⇝</td>
            <td>⇞</td>
            <td>⇟</td>
          </tr>
          <tr>
            <td>⇠</td>
            <td>⇡</td>
            <td>⇢</td>
            <td>⇣</td>
            <td>⇤</td>
            <td>⇥</td>
            <td>⇦</td>
            <td>⇧</td>
            <td>⇨</td>
            <td>⇩</td>
            <td>⇪</td>
            <td>⇫</td>
            <td>⇬</td>
            <td>⇭</td>
            <td>⇮</td>
            <td>⇯</td>
          </tr>
          <tr>
            <td>⇰</td>
            <td>⇱</td>
            <td>⇲</td>
            <td>⇳</td>
            <td>⇴</td>
            <td>⇵</td>
            <td>⇶</td>
            <td>⇷</td>
            <td>⇸</td>
            <td>⇹</td>
            <td>⇺</td>
            <td>⇻</td>
            <td>⇼</td>
            <td>⇽</td>
            <td>⇾</td>
            <td>⇿</td>
          </tr>
          <tr className="bg-slate-400 text-black">
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>a</td>
            <td>b</td>
            <td>c</td>
            <td>d</td>
            <td>e</td>
            <td>f</td>
          </tr>
          <tr>
            <td>∀</td>
            <td>∁</td>
            <td>∂</td>
            <td>∃</td>
            <td>∄</td>
            <td>∅</td>
            <td>∆</td>
            <td>∇</td>
            <td>∈</td>
            <td>∉</td>
            <td>∊</td>
            <td>∋</td>
            <td>∌</td>
            <td>∍</td>
            <td>∎</td>
            <td>∏</td>
          </tr>
          <tr>
            <td>∐</td>
            <td>∑</td>
            <td>−</td>
            <td>∓</td>
            <td>∔</td>
            <td>∕</td>
            <td>∖</td>
            <td>∗</td>
            <td>∘</td>
            <td>∙</td>
            <td>√</td>
            <td>∛</td>
            <td>∜</td>
            <td>∝</td>
            <td>∞</td>
            <td>∟</td>
          </tr>
          <tr>
            <td>∠</td>
            <td>∡</td>
            <td>∢</td>
            <td>∣</td>
            <td>∤</td>
            <td>∥</td>
            <td>∦</td>
            <td>∧</td>
            <td>∨</td>
            <td>∩</td>
            <td>∪</td>
            <td>∫</td>
            <td>∬</td>
            <td>∭</td>
            <td>∮</td>
            <td>∯</td>
          </tr>
          <tr>
            <td>∰</td>
            <td>∱</td>
            <td>∲</td>
            <td>∳</td>
            <td>∴</td>
            <td>∵</td>
            <td>∶</td>
            <td>∷</td>
            <td>∸</td>
            <td>∹</td>
            <td>∺</td>
            <td>∻</td>
            <td>∼</td>
            <td>∽</td>
            <td>∾</td>
            <td>∿</td>
          </tr>
          <tr>
            <td>≀</td>
            <td>≁</td>
            <td>≂</td>
            <td>≃</td>
            <td>≄</td>
            <td>≅</td>
            <td>≆</td>
            <td>≇</td>
            <td>≈</td>
            <td>≉</td>
            <td>≊</td>
            <td>≋</td>
            <td>≌</td>
            <td>≍</td>
            <td>≎</td>
            <td>≏</td>
          </tr>
          <tr>
            <td>≐</td>
            <td>≑</td>
            <td>≒</td>
            <td>≓</td>
            <td>≔</td>
            <td>≕</td>
            <td>≖</td>
            <td>≗</td>
            <td>≘</td>
            <td>≙</td>
            <td>≚</td>
            <td>≛</td>
            <td>≜</td>
            <td>≝</td>
            <td>≞</td>
            <td>≟</td>
          </tr>
          <tr>
            <td>≠</td>
            <td>≡</td>
            <td>≢</td>
            <td>≣</td>
            <td>≤</td>
            <td>≥</td>
            <td>≦</td>
            <td>≧</td>
            <td>≨</td>
            <td>≩</td>
            <td>≪</td>
            <td>≫</td>
            <td>≬</td>
            <td>≭</td>
            <td>≮</td>
            <td>≯</td>
          </tr>
          <tr>
            <td>≰</td>
            <td>≱</td>
            <td>≲</td>
            <td>≳</td>
            <td>≴</td>
            <td>≵</td>
            <td>≶</td>
            <td>≷</td>
            <td>≸</td>
            <td>≹</td>
            <td>≺</td>
            <td>≻</td>
            <td>≼</td>
            <td>≽</td>
            <td>≾</td>
            <td>≿</td>
          </tr>
          <tr>
            <td>⊀</td>
            <td>⊁</td>
            <td>⊂</td>
            <td>⊃</td>
            <td>⊄</td>
            <td>⊅</td>
            <td>⊆</td>
            <td>⊇</td>
            <td>⊈</td>
            <td>⊉</td>
            <td>⊊</td>
            <td>⊋</td>
            <td>⊌</td>
            <td>⊍</td>
            <td>⊎</td>
            <td>⊏</td>
          </tr>
          <tr>
            <td>⊐</td>
            <td>⊑</td>
            <td>⊒</td>
            <td>⊓</td>
            <td>⊔</td>
            <td>⊕</td>
            <td>⊖</td>
            <td>⊗</td>
            <td>⊘</td>
            <td>⊙</td>
            <td>⊚</td>
            <td>⊛</td>
            <td>⊜</td>
            <td>⊝</td>
            <td>⊞</td>
            <td>⊟</td>
          </tr>
          <tr>
            <td>⊠</td>
            <td>⊡</td>
            <td>⊢</td>
            <td>⊣</td>
            <td>⊤</td>
            <td>⊥</td>
            <td>⊦</td>
            <td>⊧</td>
            <td>⊨</td>
            <td>⊩</td>
            <td>⊪</td>
            <td>⊫</td>
            <td>⊬</td>
            <td>⊭</td>
            <td>⊮</td>
            <td>⊯</td>
          </tr>
          <tr>
            <td>⊰</td>
            <td>⊱</td>
            <td>⊲</td>
            <td>⊳</td>
            <td>⊴</td>
            <td>⊵</td>
            <td>⊶</td>
            <td>⊷</td>
            <td>⊸</td>
            <td>⊹</td>
            <td>⊺</td>
            <td>⊻</td>
            <td>⊼</td>
            <td>⊽</td>
            <td>⊾</td>
            <td>⊿</td>
          </tr>
          <tr>
            <td>⋀</td>
            <td>⋁</td>
            <td>⋂</td>
            <td>⋃</td>
            <td>⋄</td>
            <td>⋅</td>
            <td>⋆</td>
            <td>⋇</td>
            <td>⋈</td>
            <td>⋉</td>
            <td>⋊</td>
            <td>⋋</td>
            <td>⋌</td>
            <td>⋍</td>
            <td>⋎</td>
            <td>⋏</td>
          </tr>
          <tr>
            <td>⋐</td>
            <td>⋑</td>
            <td>⋒</td>
            <td>⋓</td>
            <td>⋔</td>
            <td>⋕</td>
            <td>⋖</td>
            <td>⋗</td>
            <td>⋘</td>
            <td>⋙</td>
            <td>⋚</td>
            <td>⋛</td>
            <td>⋜</td>
            <td>⋝</td>
            <td>⋞</td>
            <td>⋟</td>
          </tr>
          <tr>
            <td>⋠</td>
            <td>⋡</td>
            <td>⋢</td>
            <td>⋣</td>
            <td>⋤</td>
            <td>⋥</td>
            <td>⋦</td>
            <td>⋧</td>
            <td>⋨</td>
            <td>⋩</td>
            <td>⋪</td>
            <td>⋫</td>
            <td>⋬</td>
            <td>⋭</td>
            <td>⋮</td>
            <td>⋯</td>
          </tr>
          <tr>
            <td>⋰</td>
            <td>⋱</td>
            <td>⋲</td>
            <td>⋳</td>
            <td>⋴</td>
            <td>⋵</td>
            <td>⋶</td>
            <td>⋷</td>
            <td>⋸</td>
            <td>⋹</td>
            <td>⋺</td>
            <td>⋻</td>
            <td>⋼</td>
            <td>⋽</td>
            <td>⋾</td>
            <td>⋿</td>
          </tr>
          <tr>
            <td>⌀</td>
            <td>⌁</td>
            <td>⌂</td>
            <td>⌃</td>
            <td>⌄</td>
            <td>⌅</td>
            <td>⌆</td>
            <td>⌇</td>
            <td>⌈</td>
            <td>⌉</td>
            <td>⌊</td>
            <td>⌋</td>
            <td>⌌</td>
            <td>⌍</td>
            <td>⌎</td>
            <td>⌏</td>
          </tr>
          <tr>
            <td>⌐</td>
            <td>⌑</td>
            <td>⌒</td>
            <td>⌓</td>
            <td>⌔</td>
            <td>⌕</td>
            <td>⌖</td>
            <td>⌗</td>
            <td>⌘</td>
            <td>⌙</td>
            <td>⌚</td>
            <td>⌛</td>
            <td>⌜</td>
            <td>⌝</td>
            <td>⌞</td>
            <td>⌟</td>
          </tr>
          <tr>
            <td>⌠</td>
            <td>⌡</td>
            <td>⌢</td>
            <td>⌣</td>
            <td>⌤</td>
            <td>⌥</td>
            <td>⌦</td>
            <td>⌧</td>
            <td>⌨</td>
            <td>〈</td>
            <td>〉</td>
            <td>⌫</td>
            <td>⌬</td>
            <td>⌭</td>
            <td>⌮</td>
            <td>⌯</td>
          </tr>
          <tr>
            <td>⌰</td>
            <td>⌱</td>
            <td>⌲</td>
            <td>⌳</td>
            <td>⌴</td>
            <td>⌵</td>
            <td>⌶</td>
            <td>⌷</td>
            <td>⌸</td>
            <td>⌹</td>
            <td>⌺</td>
            <td>⌻</td>
            <td>⌼</td>
            <td>⌽</td>
            <td>⌾</td>
            <td>⌿</td>
          </tr>
          <tr>
            <td>⍀</td>
            <td>⍁</td>
            <td>⍂</td>
            <td>⍃</td>
            <td>⍄</td>
            <td>⍅</td>
            <td>⍆</td>
            <td>⍇</td>
            <td>⍈</td>
            <td>⍉</td>
            <td>⍊</td>
            <td>⍋</td>
            <td>⍌</td>
            <td>⍍</td>
            <td>⍎</td>
            <td>⍏</td>
          </tr>
          <tr>
            <td>⍐</td>
            <td>⍑</td>
            <td>⍒</td>
            <td>⍓</td>
            <td>⍔</td>
            <td>⍕</td>
            <td>⍖</td>
            <td>⍗</td>
            <td>⍘</td>
            <td>⍙</td>
            <td>⍚</td>
            <td>⍛</td>
            <td>⍜</td>
            <td>⍝</td>
            <td>⍞</td>
            <td>⍟</td>
          </tr>
          <tr>
            <td>⍠</td>
            <td>⍡</td>
            <td>⍢</td>
            <td>⍣</td>
            <td>⍤</td>
            <td>⍥</td>
            <td>⍦</td>
            <td>⍧</td>
            <td>⍨</td>
            <td>⍩</td>
            <td>⍪</td>
            <td>⍫</td>
            <td>⍬</td>
            <td>⍭</td>
            <td>⍮</td>
            <td>⍯</td>
          </tr>
          <tr>
            <td>⍰</td>
            <td>⍱</td>
            <td>⍲</td>
            <td>⍳</td>
            <td>⍴</td>
            <td>⍵</td>
            <td>⍶</td>
            <td>⍷</td>
            <td>⍸</td>
            <td>⍹</td>
            <td>⍺</td>
            <td>⍻</td>
            <td>⍼</td>
            <td>⍽</td>
            <td>⍾</td>
            <td>⍿</td>
          </tr>
          <tr>
            <td>⎀</td>
            <td>⎁</td>
            <td>⎂</td>
            <td>⎃</td>
            <td>⎄</td>
            <td>⎅</td>
            <td>⎆</td>
            <td>⎇</td>
            <td>⎈</td>
            <td>⎉</td>
            <td>⎊</td>
            <td>⎋</td>
            <td>⎌</td>
            <td>⎍</td>
            <td>⎎</td>
            <td>⎏</td>
          </tr>
          <tr>
            <td>⎐</td>
            <td>⎑</td>
            <td>⎒</td>
            <td>⎓</td>
            <td>⎔</td>
            <td>⎕</td>
            <td>⎖</td>
            <td>⎗</td>
            <td>⎘</td>
            <td>⎙</td>
            <td>⎚</td>
            <td>⎛</td>
            <td>⎜</td>
            <td>⎝</td>
            <td>⎞</td>
            <td>⎟</td>
          </tr>
          <tr>
            <td>⎠</td>
            <td>⎡</td>
            <td>⎢</td>
            <td>⎣</td>
            <td>⎤</td>
            <td>⎥</td>
            <td>⎦</td>
            <td>⎧</td>
            <td>⎨</td>
            <td>⎩</td>
            <td>⎪</td>
            <td>⎫</td>
            <td>⎬</td>
            <td>⎭</td>
            <td>⎮</td>
            <td>⎯</td>
          </tr>
          <tr>
            <td>⎰</td>
            <td>⎱</td>
            <td>⎲</td>
            <td>⎳</td>
            <td>⎴</td>
            <td>⎵</td>
            <td>⎶</td>
            <td>⎷</td>
            <td>⎸</td>
            <td>⎹</td>
            <td>⎺</td>
            <td>⎻</td>
            <td>⎼</td>
            <td>⎽</td>
            <td>⎾</td>
            <td>⎿</td>
          </tr>
          <tr>
            <td>⏀</td>
            <td>⏁</td>
            <td>⏂</td>
            <td>⏃</td>
            <td>⏄</td>
            <td>⏅</td>
            <td>⏆</td>
            <td>⏇</td>
            <td>⏈</td>
            <td>⏉</td>
            <td>⏊</td>
            <td>⏋</td>
            <td>⏌</td>
            <td>⏍</td>
            <td>⏎</td>
            <td>⏏</td>
          </tr>
          <tr>
            <td>⏐</td>
            <td>⏑</td>
            <td>⏒</td>
            <td>⏓</td>
            <td>⏔</td>
            <td>⏕</td>
            <td>⏖</td>
            <td>⏗</td>
            <td>⏘</td>
            <td>⏙</td>
            <td>⏚</td>
            <td>⏛</td>
            <td>⏜</td>
            <td>⏝</td>
            <td>⏞</td>
            <td>⏟</td>
          </tr>
          <tr>
            <td>⏠</td>
            <td>⏡</td>
            <td>⏢</td>
            <td>⏣</td>
            <td>⏤</td>
            <td>⏥</td>
            <td>⏦</td>
            <td>⏧</td>
            <td>⏨</td>
            <td>⏩</td>
            <td>⏪</td>
            <td>⏫</td>
            <td>⏬</td>
            <td>⏭</td>
            <td>⏮</td>
            <td>⏯</td>
          </tr>
          <tr>
            <td>⏰</td>
            <td>⏱</td>
            <td>⏲</td>
            <td>⏳</td>
            <td>⏴</td>
            <td>⏵</td>
            <td>⏶</td>
            <td>⏷</td>
            <td>⏸</td>
            <td>⏹</td>
            <td>⏺</td>
            <td>⏻</td>
            <td>⏼</td>
            <td>⏽</td>
            <td>⏾</td>
            <td>⏿</td>
          </tr>
          <tr className="bg-slate-400 text-black">
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>a</td>
            <td>b</td>
            <td>c</td>
            <td>d</td>
            <td>e</td>
            <td>f</td>
          </tr>
          <tr>
            <td>␀</td>
            <td>␁</td>
            <td>␂</td>
            <td>␃</td>
            <td>␄</td>
            <td>␅</td>
            <td>␆</td>
            <td>␇</td>
            <td>␈</td>
            <td>␉</td>
            <td>␊</td>
            <td>␋</td>
            <td>␌</td>
            <td>␍</td>
            <td>␎</td>
            <td>␏</td>
          </tr>
          <tr>
            <td>␐</td>
            <td>␑</td>
            <td>␒</td>
            <td>␓</td>
            <td>␔</td>
            <td>␕</td>
            <td>␖</td>
            <td>␗</td>
            <td>␘</td>
            <td>␙</td>
            <td>␚</td>
            <td>␛</td>
            <td>␜</td>
            <td>␝</td>
            <td>␞</td>
            <td>␟</td>
          </tr>
          <tr>
            <td>␠</td>
            <td>␡</td>
            <td>␢</td>
            <td>␣</td>
            <td>␤</td>
            <td>␥</td>
            <td>␦</td>
            <td>␧</td>
            <td>␨</td>
            <td>␩</td>
            <td>␪</td>
            <td>␫</td>
            <td>␬</td>
            <td>␭</td>
            <td>␮</td>
            <td>␯</td>
          </tr>
          <tr>
            <td>␰</td>
            <td>␱</td>
            <td>␲</td>
            <td>␳</td>
            <td>␴</td>
            <td>␵</td>
            <td>␶</td>
            <td>␷</td>
            <td>␸</td>
            <td>␹</td>
            <td>␺</td>
            <td>␻</td>
            <td>␼</td>
            <td>␽</td>
            <td>␾</td>
            <td>␿</td>
          </tr>
          <tr>
            <td>⑀</td>
            <td>⑁</td>
            <td>⑂</td>
            <td>⑃</td>
            <td>⑄</td>
            <td>⑅</td>
            <td>⑆</td>
            <td>⑇</td>
            <td>⑈</td>
            <td>⑉</td>
            <td>⑊</td>
            <td>⑋</td>
            <td>⑌</td>
            <td>⑍</td>
            <td>⑎</td>
            <td>⑏</td>
          </tr>
          <tr>
            <td>⑐</td>
            <td>⑑</td>
            <td>⑒</td>
            <td>⑓</td>
            <td>⑔</td>
            <td>⑕</td>
            <td>⑖</td>
            <td>⑗</td>
            <td>⑘</td>
            <td>⑙</td>
            <td>⑚</td>
            <td>⑛</td>
            <td>⑜</td>
            <td>⑝</td>
            <td>⑞</td>
            <td>⑟</td>
          </tr>
          <tr>
            <td>①</td>
            <td>②</td>
            <td>③</td>
            <td>④</td>
            <td>⑤</td>
            <td>⑥</td>
            <td>⑦</td>
            <td>⑧</td>
            <td>⑨</td>
            <td>⑩</td>
            <td>⑪</td>
            <td>⑫</td>
            <td>⑬</td>
            <td>⑭</td>
            <td>⑮</td>
            <td>⑯</td>
          </tr>
          <tr>
            <td>⑰</td>
            <td>⑱</td>
            <td>⑲</td>
            <td>⑳</td>
            <td>⑴</td>
            <td>⑵</td>
            <td>⑶</td>
            <td>⑷</td>
            <td>⑸</td>
            <td>⑹</td>
            <td>⑺</td>
            <td>⑻</td>
            <td>⑼</td>
            <td>⑽</td>
            <td>⑾</td>
            <td>⑿</td>
          </tr>
          <tr>
            <td>⒀</td>
            <td>⒁</td>
            <td>⒂</td>
            <td>⒃</td>
            <td>⒄</td>
            <td>⒅</td>
            <td>⒆</td>
            <td>⒇</td>
            <td>⒈</td>
            <td>⒉</td>
            <td>⒊</td>
            <td>⒋</td>
            <td>⒌</td>
            <td>⒍</td>
            <td>⒎</td>
            <td>⒏</td>
          </tr>
          <tr>
            <td>⒐</td>
            <td>⒑</td>
            <td>⒒</td>
            <td>⒓</td>
            <td>⒔</td>
            <td>⒕</td>
            <td>⒖</td>
            <td>⒗</td>
            <td>⒘</td>
            <td>⒙</td>
            <td>⒚</td>
            <td>⒛</td>
            <td>⒜</td>
            <td>⒝</td>
            <td>⒞</td>
            <td>⒟</td>
          </tr>
          <tr>
            <td>⒠</td>
            <td>⒡</td>
            <td>⒢</td>
            <td>⒣</td>
            <td>⒤</td>
            <td>⒥</td>
            <td>⒦</td>
            <td>⒧</td>
            <td>⒨</td>
            <td>⒩</td>
            <td>⒪</td>
            <td>⒫</td>
            <td>⒬</td>
            <td>⒭</td>
            <td>⒮</td>
            <td>⒯</td>
          </tr>
          <tr>
            <td>⒰</td>
            <td>⒱</td>
            <td>⒲</td>
            <td>⒳</td>
            <td>⒴</td>
            <td>⒵</td>
            <td>Ⓐ</td>
            <td>Ⓑ</td>
            <td>Ⓒ</td>
            <td>Ⓓ</td>
            <td>Ⓔ</td>
            <td>Ⓕ</td>
            <td>Ⓖ</td>
            <td>Ⓗ</td>
            <td>Ⓘ</td>
            <td>Ⓙ</td>
          </tr>
          <tr>
            <td>Ⓚ</td>
            <td>Ⓛ</td>
            <td>Ⓜ</td>
            <td>Ⓝ</td>
            <td>Ⓞ</td>
            <td>Ⓟ</td>
            <td>Ⓠ</td>
            <td>Ⓡ</td>
            <td>Ⓢ</td>
            <td>Ⓣ</td>
            <td>Ⓤ</td>
            <td>Ⓥ</td>
            <td>Ⓦ</td>
            <td>Ⓧ</td>
            <td>Ⓨ</td>
            <td>Ⓩ</td>
          </tr>
          <tr>
            <td>ⓐ</td>
            <td>ⓑ</td>
            <td>ⓒ</td>
            <td>ⓓ</td>
            <td>ⓔ</td>
            <td>ⓕ</td>
            <td>ⓖ</td>
            <td>ⓗ</td>
            <td>ⓘ</td>
            <td>ⓙ</td>
            <td>ⓚ</td>
            <td>ⓛ</td>
            <td>ⓜ</td>
            <td>ⓝ</td>
            <td>ⓞ</td>
            <td>ⓟ</td>
          </tr>
          <tr>
            <td>ⓠ</td>
            <td>ⓡ</td>
            <td>ⓢ</td>
            <td>ⓣ</td>
            <td>ⓤ</td>
            <td>ⓥ</td>
            <td>ⓦ</td>
            <td>ⓧ</td>
            <td>ⓨ</td>
            <td>ⓩ</td>
            <td>⓪</td>
            <td>⓫</td>
            <td>⓬</td>
            <td>⓭</td>
            <td>⓮</td>
            <td>⓯</td>
          </tr>
          <tr>
            <td>⓰</td>
            <td>⓱</td>
            <td>⓲</td>
            <td>⓳</td>
            <td>⓴</td>
            <td>⓵</td>
            <td>⓶</td>
            <td>⓷</td>
            <td>⓸</td>
            <td>⓹</td>
            <td>⓺</td>
            <td>⓻</td>
            <td>⓼</td>
            <td>⓽</td>
            <td>⓾</td>
            <td>⓿</td>
          </tr>
          <tr>
            <td>─</td>
            <td>━</td>
            <td>│</td>
            <td>┃</td>
            <td>┄</td>
            <td>┅</td>
            <td>┆</td>
            <td>┇</td>
            <td>┈</td>
            <td>┉</td>
            <td>┊</td>
            <td>┋</td>
            <td>┌</td>
            <td>┍</td>
            <td>┎</td>
            <td>┏</td>
          </tr>
          <tr>
            <td>┐</td>
            <td>┑</td>
            <td>┒</td>
            <td>┓</td>
            <td>└</td>
            <td>┕</td>
            <td>┖</td>
            <td>┗</td>
            <td>┘</td>
            <td>┙</td>
            <td>┚</td>
            <td>┛</td>
            <td>├</td>
            <td>┝</td>
            <td>┞</td>
            <td>┟</td>
          </tr>
          <tr>
            <td>┠</td>
            <td>┡</td>
            <td>┢</td>
            <td>┣</td>
            <td>┤</td>
            <td>┥</td>
            <td>┦</td>
            <td>┧</td>
            <td>┨</td>
            <td>┩</td>
            <td>┪</td>
            <td>┫</td>
            <td>┬</td>
            <td>┭</td>
            <td>┮</td>
            <td>┯</td>
          </tr>
          <tr>
            <td>┰</td>
            <td>┱</td>
            <td>┲</td>
            <td>┳</td>
            <td>┴</td>
            <td>┵</td>
            <td>┶</td>
            <td>┷</td>
            <td>┸</td>
            <td>┹</td>
            <td>┺</td>
            <td>┻</td>
            <td>┼</td>
            <td>┽</td>
            <td>┾</td>
            <td>┿</td>
          </tr>
          <tr>
            <td>╀</td>
            <td>╁</td>
            <td>╂</td>
            <td>╃</td>
            <td>╄</td>
            <td>╅</td>
            <td>╆</td>
            <td>╇</td>
            <td>╈</td>
            <td>╉</td>
            <td>╊</td>
            <td>╋</td>
            <td>╌</td>
            <td>╍</td>
            <td>╎</td>
            <td>╏</td>
          </tr>
          <tr>
            <td>═</td>
            <td>║</td>
            <td>╒</td>
            <td>╓</td>
            <td>╔</td>
            <td>╕</td>
            <td>╖</td>
            <td>╗</td>
            <td>╘</td>
            <td>╙</td>
            <td>╚</td>
            <td>╛</td>
            <td>╜</td>
            <td>╝</td>
            <td>╞</td>
            <td>╟</td>
          </tr>
          <tr>
            <td>╠</td>
            <td>╡</td>
            <td>╢</td>
            <td>╣</td>
            <td>╤</td>
            <td>╥</td>
            <td>╦</td>
            <td>╧</td>
            <td>╨</td>
            <td>╩</td>
            <td>╪</td>
            <td>╫</td>
            <td>╬</td>
            <td>╭</td>
            <td>╮</td>
            <td>╯</td>
          </tr>
          <tr>
            <td>╰</td>
            <td>╱</td>
            <td>╲</td>
            <td>╳</td>
            <td>╴</td>
            <td>╵</td>
            <td>╶</td>
            <td>╷</td>
            <td>╸</td>
            <td>╹</td>
            <td>╺</td>
            <td>╻</td>
            <td>╼</td>
            <td>╽</td>
            <td>╾</td>
            <td>╿</td>
          </tr>
          <tr>
            <td>▀</td>
            <td>▁</td>
            <td>▂</td>
            <td>▃</td>
            <td>▄</td>
            <td>▅</td>
            <td>▆</td>
            <td>▇</td>
            <td>█</td>
            <td>▉</td>
            <td>▊</td>
            <td>▋</td>
            <td>▌</td>
            <td>▍</td>
            <td>▎</td>
            <td>▏</td>
          </tr>
          <tr>
            <td>▐</td>
            <td>░</td>
            <td>▒</td>
            <td>▓</td>
            <td>▔</td>
            <td>▕</td>
            <td>▖</td>
            <td>▗</td>
            <td>▘</td>
            <td>▙</td>
            <td>▚</td>
            <td>▛</td>
            <td>▜</td>
            <td>▝</td>
            <td>▞</td>
            <td>▟</td>
          </tr>
          <tr>
            <td>■</td>
            <td>□</td>
            <td>▢</td>
            <td>▣</td>
            <td>▤</td>
            <td>▥</td>
            <td>▦</td>
            <td>▧</td>
            <td>▨</td>
            <td>▩</td>
            <td>▪</td>
            <td>▫</td>
            <td>▬</td>
            <td>▭</td>
            <td>▮</td>
            <td>▯</td>
          </tr>
          <tr>
            <td>▰</td>
            <td>▱</td>
            <td>▲</td>
            <td>△</td>
            <td>▴</td>
            <td>▵</td>
            <td>▶</td>
            <td>▷</td>
            <td>▸</td>
            <td>▹</td>
            <td>►</td>
            <td>▻</td>
            <td>▼</td>
            <td>▽</td>
            <td>▾</td>
            <td>▿</td>
          </tr>
          <tr>
            <td>◀</td>
            <td>◁</td>
            <td>◂</td>
            <td>◃</td>
            <td>◄</td>
            <td>◅</td>
            <td>◆</td>
            <td>◇</td>
            <td>◈</td>
            <td>◉</td>
            <td>◊</td>
            <td>○</td>
            <td>◌</td>
            <td>◍</td>
            <td>◎</td>
            <td>●</td>
          </tr>
          <tr>
            <td>◐</td>
            <td>◑</td>
            <td>◒</td>
            <td>◓</td>
            <td>◔</td>
            <td>◕</td>
            <td>◖</td>
            <td>◗</td>
            <td>◘</td>
            <td>◙</td>
            <td>◚</td>
            <td>◛</td>
            <td>◜</td>
            <td>◝</td>
            <td>◞</td>
            <td>◟</td>
          </tr>
          <tr>
            <td>◠</td>
            <td>◡</td>
            <td>◢</td>
            <td>◣</td>
            <td>◤</td>
            <td>◥</td>
            <td>◦</td>
            <td>◧</td>
            <td>◨</td>
            <td>◩</td>
            <td>◪</td>
            <td>◫</td>
            <td>◬</td>
            <td>◭</td>
            <td>◮</td>
            <td>◯</td>
          </tr>
          <tr>
            <td>◰</td>
            <td>◱</td>
            <td>◲</td>
            <td>◳</td>
            <td>◴</td>
            <td>◵</td>
            <td>◶</td>
            <td>◷</td>
            <td>◸</td>
            <td>◹</td>
            <td>◺</td>
            <td>◻</td>
            <td>◼</td>
            <td>◽</td>
            <td>◾</td>
            <td>◿</td>
          </tr>
          <tr className="bg-slate-400 text-black">
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>a</td>
            <td>b</td>
            <td>c</td>
            <td>d</td>
            <td>e</td>
            <td>f</td>
          </tr>
          <tr>
            <td>☀</td>
            <td>☁</td>
            <td>☂</td>
            <td>☃</td>
            <td>☄</td>
            <td>★</td>
            <td>☆</td>
            <td>☇</td>
            <td>☈</td>
            <td>☉</td>
            <td>☊</td>
            <td>☋</td>
            <td>☌</td>
            <td>☍</td>
            <td>☎</td>
            <td>☏</td>
          </tr>
          <tr>
            <td>☐</td>
            <td>☑</td>
            <td>☒</td>
            <td>☓</td>
            <td>☔</td>
            <td>☕</td>
            <td>☖</td>
            <td>☗</td>
            <td>☘</td>
            <td>☙</td>
            <td>☚</td>
            <td>☛</td>
            <td>☜</td>
            <td>☝</td>
            <td>☞</td>
            <td>☟</td>
          </tr>
          <tr>
            <td>☠</td>
            <td>☡</td>
            <td>☢</td>
            <td>☣</td>
            <td>☤</td>
            <td>☥</td>
            <td>☦</td>
            <td>☧</td>
            <td>☨</td>
            <td>☩</td>
            <td>☪</td>
            <td>☫</td>
            <td>☬</td>
            <td>☭</td>
            <td>☮</td>
            <td>☯</td>
          </tr>
          <tr>
            <td>☰</td>
            <td>☱</td>
            <td>☲</td>
            <td>☳</td>
            <td>☴</td>
            <td>☵</td>
            <td>☶</td>
            <td>☷</td>
            <td>☸</td>
            <td>☹</td>
            <td>☺</td>
            <td>☻</td>
            <td>☼</td>
            <td>☽</td>
            <td>☾</td>
            <td>☿</td>
          </tr>
          <tr>
            <td>♀</td>
            <td>♁</td>
            <td>♂</td>
            <td>♃</td>
            <td>♄</td>
            <td>♅</td>
            <td>♆</td>
            <td>♇</td>
            <td>♈</td>
            <td>♉</td>
            <td>♊</td>
            <td>♋</td>
            <td>♌</td>
            <td>♍</td>
            <td>♎</td>
            <td>♏</td>
          </tr>
          <tr>
            <td>♐</td>
            <td>♑</td>
            <td>♒</td>
            <td>♓</td>
            <td>♔</td>
            <td>♕</td>
            <td>♖</td>
            <td>♗</td>
            <td>♘</td>
            <td>♙</td>
            <td>♚</td>
            <td>♛</td>
            <td>♜</td>
            <td>♝</td>
            <td>♞</td>
            <td>♟</td>
          </tr>
          <tr>
            <td>♠</td>
            <td>♡</td>
            <td>♢</td>
            <td>♣</td>
            <td>♤</td>
            <td>♥</td>
            <td>♦</td>
            <td>♧</td>
            <td>♨</td>
            <td>♩</td>
            <td>♪</td>
            <td>♫</td>
            <td>♬</td>
            <td>♭</td>
            <td>♮</td>
            <td>♯</td>
          </tr>
          <tr>
            <td>♰</td>
            <td>♱</td>
            <td>♲</td>
            <td>♳</td>
            <td>♴</td>
            <td>♵</td>
            <td>♶</td>
            <td>♷</td>
            <td>♸</td>
            <td>♹</td>
            <td>♺</td>
            <td>♻</td>
            <td>♼</td>
            <td>♽</td>
            <td>♾</td>
            <td>♿</td>
          </tr>
          <tr>
            <td>⚀</td>
            <td>⚁</td>
            <td>⚂</td>
            <td>⚃</td>
            <td>⚄</td>
            <td>⚅</td>
            <td>⚆</td>
            <td>⚇</td>
            <td>⚈</td>
            <td>⚉</td>
            <td>⚊</td>
            <td>⚋</td>
            <td>⚌</td>
            <td>⚍</td>
            <td>⚎</td>
            <td>⚏</td>
          </tr>
          <tr>
            <td>⚐</td>
            <td>⚑</td>
            <td>⚒</td>
            <td>⚓</td>
            <td>⚔</td>
            <td>⚕</td>
            <td>⚖</td>
            <td>⚗</td>
            <td>⚘</td>
            <td>⚙</td>
            <td>⚚</td>
            <td>⚛</td>
            <td>⚜</td>
            <td>⚝</td>
            <td>⚞</td>
            <td>⚟</td>
          </tr>
          <tr>
            <td>⚠</td>
            <td>⚡</td>
            <td>⚢</td>
            <td>⚣</td>
            <td>⚤</td>
            <td>⚥</td>
            <td>⚦</td>
            <td>⚧</td>
            <td>⚨</td>
            <td>⚩</td>
            <td>⚪</td>
            <td>⚫</td>
            <td>⚬</td>
            <td>⚭</td>
            <td>⚮</td>
            <td>⚯</td>
          </tr>
          <tr>
            <td>⚰</td>
            <td>⚱</td>
            <td>⚲</td>
            <td>⚳</td>
            <td>⚴</td>
            <td>⚵</td>
            <td>⚶</td>
            <td>⚷</td>
            <td>⚸</td>
            <td>⚹</td>
            <td>⚺</td>
            <td>⚻</td>
            <td>⚼</td>
            <td>⚽</td>
            <td>⚾</td>
            <td>⚿</td>
          </tr>
          <tr>
            <td>⛀</td>
            <td>⛁</td>
            <td>⛂</td>
            <td>⛃</td>
            <td>⛄</td>
            <td>⛅</td>
            <td>⛆</td>
            <td>⛇</td>
            <td>⛈</td>
            <td>⛉</td>
            <td>⛊</td>
            <td>⛋</td>
            <td>⛌</td>
            <td>⛍</td>
            <td>⛎</td>
            <td>⛏</td>
          </tr>
          <tr>
            <td>⛐</td>
            <td>⛑</td>
            <td>⛒</td>
            <td>⛓</td>
            <td>⛔</td>
            <td>⛕</td>
            <td>⛖</td>
            <td>⛗</td>
            <td>⛘</td>
            <td>⛙</td>
            <td>⛚</td>
            <td>⛛</td>
            <td>⛜</td>
            <td>⛝</td>
            <td>⛞</td>
            <td>⛟</td>
          </tr>
          <tr>
            <td>⛠</td>
            <td>⛡</td>
            <td>⛢</td>
            <td>⛣</td>
            <td>⛤</td>
            <td>⛥</td>
            <td>⛦</td>
            <td>⛧</td>
            <td>⛨</td>
            <td>⛩</td>
            <td>⛪</td>
            <td>⛫</td>
            <td>⛬</td>
            <td>⛭</td>
            <td>⛮</td>
            <td>⛯</td>
          </tr>
          <tr>
            <td>⛰</td>
            <td>⛱</td>
            <td>⛲</td>
            <td>⛳</td>
            <td>⛴</td>
            <td>⛵</td>
            <td>⛶</td>
            <td>⛷</td>
            <td>⛸</td>
            <td>⛹</td>
            <td>⛺</td>
            <td>⛻</td>
            <td>⛼</td>
            <td>⛽</td>
            <td>⛾</td>
            <td>⛿</td>
          </tr>
          <tr>
            <td>✀</td>
            <td>✁</td>
            <td>✂</td>
            <td>✃</td>
            <td>✄</td>
            <td>✅</td>
            <td>✆</td>
            <td>✇</td>
            <td>✈</td>
            <td>✉</td>
            <td>✊</td>
            <td>✋</td>
            <td>✌</td>
            <td>✍</td>
            <td>✎</td>
            <td>✏</td>
          </tr>
        </tbody>
      </table>
    </section>
  );
};
export default SpecialCharacters;
